import { isolateLtr } from "../ui/bidi.js";

export type SetupCopyLocale = "en" | "ar";

export type SetupCopyRiskSurface =
  | "none"
  | "interface-preference"
  | "workspace-path"
  | "workspace-trust"
  | "provider-selection"
  | "credential-reference"
  | "security-policy"
  | "workflow-learning"
  | "optional-capability"
  | "setup-review"
  | "config-write"
  | "setup-verification"
  | "agent-launch"
  | "config-summary"
  | "config-repair"
  | "varies";

export type SetupCopyEntry = {
  readonly key: string;
  readonly en: string;
  readonly ar: string;
  readonly placeholders: readonly string[];
  readonly ltrPlaceholders: readonly string[];
  readonly riskSurface: SetupCopyRiskSurface;
  readonly mvp: boolean;
  readonly notes?: string;
};

export type SetupCopyResolutionOptions = {
  readonly isolateArabicTechnicalTokens?: boolean;
};

const TECHNICAL_TOKENS = [
  "estacoda setup --advanced --provider <provider> --model <model> --api-key-env <ENV_NAME>",
  "estacoda setup --provider deepseek --model deepseek-chat --api-key-env DEEPSEEK_API_KEY",
  "estacoda telegram setup",
  "estacoda browser setup",
  "estacoda setup --advanced",
  "chmod 600 <secret-store>",
  "ESTACODA_TELEGRAM_BOT_TOKEN",
  "/workspace.trust.grant",
  "@BotFather",
  "BotFather",
  "@userinfobot",
  "@getidsbot",
  "@chatIDrobot",
  "/newbot",
  "/start",
  "http://127.0.0.1:9222",
  "fal-ai/imagen4/preview",
  "provider.credentialReference",
  "provider.route",
  "memory_compaction",
  "profile_context",
  "session_search",
  "DEEPSEEK_API_KEY",
  "deepseek-chat",
  "compression",
  "assessor",
  "image gateway",
  "useGateway",
  "deepseek",
  "FAL_KEY",
  "TTS",
  "STT",
  "faster-whisper",
  "pythonBinary",
  "~/.estacoda/python-env",
  "~/.estacoda/cache/huggingface",
  "CDP",
  "estacoda verify",
  "estacoda setup",
  "EstaCoda",
  "Telegram",
  "WhatsApp",
  "Discord",
  "package.json",
  "~/.estacoda",
  "estacoda",
  "0600",
  "API",
] as const;

export const SETUP_COPY_ENTRIES = [
  copy("onboarding.welcome", "Configure the workspace, model, credentials, and safety defaults EstaCoda needs before it can run.", "اضبط مساحة العمل والنموذج وبيانات الاعتماد وإعدادات الأمان الافتراضية التي تحتاجها EstaCoda قبل التشغيل.", [], "none"),
  copy("onboarding.welcome.title", "EstaCoda Onboarding Wizard", "معالج تهيئة EstaCoda", [], "none"),
  copy("onboarding.common.begin", "Begin", "ابدأ", [], "none"),
  copy("onboarding.welcome.validation.acknowledged", "Confirm to continue setup.", "أكّد للمتابعة في الإعداد.", [], "none"),
  copy("onboarding.interfaceLanguage", "Choose the setup language and how EstaCoda speaks while working. Same engine, different style.", "اختر لغة الإعداد وكيف تتحدث EstaCoda أثناء العمل. نفس المحرك، أسلوب مختلف.", [], "interface-preference"),
  copy("onboarding.interfaceLanguage.title", "Setup language", "لغة الإعداد", [], "interface-preference"),
  copy("onboarding.interfaceLanguage.options.en.label", "English", "English", [], "interface-preference"),
  copy("onboarding.interfaceLanguage.options.en.description", "Use English setup copy.", "استخدم نصوص الإعداد الإنجليزية.", [], "interface-preference"),
  copy("onboarding.interfaceLanguage.options.ar.label", "العربية", "العربية", [], "interface-preference"),
  copy("onboarding.interfaceLanguage.options.ar.description", "Use Arabic setup copy with isolated technical tokens.", "استخدم نصوص الإعداد العربية مع عزل الرموز التقنية.", [], "interface-preference"),
  copy("onboarding.interfaceLanguage.validation.languageSelected", "Choose a setup language.", "اختر لغة الإعداد.", [], "interface-preference"),
  copy("onboarding.interfaceStyle.title", "Interface style", "أسلوب الواجهة", [], "interface-preference"),
  copy("onboarding.interfaceStyle.prompt", "Choose the default interface style.", "اختر أسلوب الواجهة الافتراضي.", [], "interface-preference"),
  copy("onboarding.interfaceStyle.standard.label", "Standard", "قياسي", [], "interface-preference"),
  copy("onboarding.interfaceStyle.standard.description", "Plain English runtime labels.", "تسميات تشغيل إنجليزية واضحة.", [], "interface-preference"),
  copy("onboarding.interfaceStyle.arabicLight.label", "Arabic-light", "عربي خفيف", [], "interface-preference"),
  copy("onboarding.interfaceStyle.arabicLight.description", "Arabic labels with stable technical tokens.", "تسميات عربية مع رموز تقنية مستقرة.", [], "interface-preference"),
  copy("onboarding.interfaceStyle.arabicStandard.description", "Standard interface style with Arabic setup copy.", "أسلوب واجهة قياسي مع نصوص إعداد عربية.", [], "interface-preference"),
  copy("onboarding.interfaceStyle.englishArabicLight.description", "English setup copy with Arabic-light visual flavor.", "نصوص إعداد إنجليزية مع لمسة بصرية عربية خفيفة.", [], "interface-preference"),
  copy("onboarding.workspace.root", "Select the workspace EstaCoda should use.", "اختر مساحة العمل التي ستعمل فيها EstaCoda.", [], "workspace-path"),
  copy("onboarding.workspace.title", "Workspace", "مساحة العمل", [], "workspace-path"),
  copy("onboarding.workspace.root.validation.selected", "Choose a workspace path.", "اختر مسار مساحة العمل.", [], "workspace-path"),
  copy("onboarding.workspace.trust", "Confirm that you want to trust the workspace: {workspacePath}", "أكّد أنك تريد الوثوق بمساحة العمل: {workspacePath}", ["{workspacePath}"], "workspace-trust"),
  copy("onboarding.workspace.trust.title", "Workspace trust", "ثقة مساحة العمل", [], "workspace-trust"),
  copy("onboarding.workspace.trustAction.label", "Trust", "ثِق", [], "workspace-trust"),
  copy("onboarding.workspace.trustAction.description", "Grant trust for this workspace after review approval.", "امنح الثقة لمساحة العمل هذه بعد موافقة المراجعة.", [], "workspace-trust"),
  copy("onboarding.workspace.changeWorkspaceAction.label", "Change Workspace", "غيّر مساحة العمل", [], "workspace-path"),
  copy("onboarding.workspace.changeWorkspaceAction.description", "Return to workspace selection.", "ارجع إلى اختيار مساحة العمل.", [], "workspace-path"),
  copy("onboarding.workspace.deferTrustAction.label", "Decide Later", "قرّر لاحقًا", [], "workspace-trust"),
  copy("onboarding.workspace.deferTrustAction.description", "Warning: the agent cannot operate in this workspace until workspace trust is granted.", "تحذير: لا يستطيع الوكيل العمل في مساحة العمل هذه حتى يتم منح الثقة.", [], "workspace-trust"),
  copy("onboarding.workspace.trust.deferredFinal", "Setup saved. Workspace trust is still required before EstaCoda can run here.", "تم حفظ الإعداد. لا تزال ثقة مساحة العمل مطلوبة قبل أن تتمكن EstaCoda من العمل هنا.", [], "workspace-trust"),
  copy("onboarding.workspace.invalid.title", "Workspace path unavailable", "مسار مساحة العمل غير متاح", [], "workspace-path"),
  copy("onboarding.workspace.invalid.tryAgain", "Try again", "حاول مرة أخرى", [], "workspace-path"),
  copy("onboarding.workspace.invalid.useCurrent", "Use current workspace", "استخدم مساحة العمل الحالية", [], "workspace-path"),
  copy("onboarding.workspace.invalid.cancel", "Cancel setup", "ألغِ الإعداد", [], "workspace-path"),
  copy("onboarding.workspace.trust.validation.explicit", "Choose clearly whether to trust this workspace. Trust is never silent.", "اختر بوضوح هل تريد الوثوق بمساحة العمل هذه. لا توجد ثقة صامتة.", [], "workspace-trust"),
  copy("onboarding.providers.primary", "Choose the provider EstaCoda should use first when it needs to think.", "اختر المزوّد الذي ستستدعيه EstaCoda أولاً عندما تحتاج إلى التفكير.", [], "provider-selection"),
  copy("onboarding.providers.primary.title", "Primary provider", "المزوّد الأساسي", [], "provider-selection"),
  copy("onboarding.providers.primary.validation.selected", "Choose a primary provider.", "اختر مزوّدًا أساسيًا.", [], "provider-selection"),
  copy("onboarding.providers.primaryModel", "Choose the primary model for {providerId}.", "اختر النموذج الأساسي للمزوّد {providerId}.", ["{providerId}"], "provider-selection"),
  copy("onboarding.providers.primaryModel.title", "Primary model", "النموذج الأساسي", [], "provider-selection"),
  copy("onboarding.providers.primaryModel.validation.selected", "Choose a primary model.", "اختر نموذجًا أساسيًا.", [], "provider-selection"),
  copy("onboarding.providers.primaryCredential", "Store a credential reference, not the secret value. EstaCoda keeps secret values out of review screens.", "احفظ مرجع بيانات الاعتماد، وليس قيمة السر نفسها. تبقي EstaCoda قيم الأسرار خارج شاشات المراجعة.", [], "credential-reference"),
  copy("onboarding.providers.primaryCredential.validation.reference", "Hosted providers need an environment variable reference such as {envVar}.", "المزوّدات المستضافة تحتاج إلى مرجع متغيّر بيئة مثل {envVar}.", ["{envVar}"], "credential-reference"),
  copy("onboarding.providers.primaryCredential.localProviderSkip", "Local provider selected, no hosted API key, no cloud ceremony.", "تم اختيار مزوّد محلي. بلا مفتاح API مستضاف، وبلا طقوس سحابية.", [], "credential-reference"),
  copy("onboarding.catalog.provider.catalogOnly", "Available in the offline catalog; runtime support may require configuration.", "متاح في الفهرس المحلي؛ قد يحتاج دعم التشغيل إلى إعداد إضافي.", [], "provider-selection"),
  copy("onboarding.catalog.provider.configured", "Configured provider.", "مزوّد مهيأ.", [], "provider-selection"),
  copy("onboarding.catalog.provider.available", "Available provider.", "مزوّد متاح.", [], "provider-selection"),
  copy("onboarding.catalog.model.features.tools", "tools", "أدوات", [], "provider-selection"),
  copy("onboarding.catalog.model.features.vision", "vision", "رؤية", [], "provider-selection"),
  copy("onboarding.catalog.model.features.reasoning", "reasoning", "استدلال", [], "provider-selection"),
  copy("onboarding.security", "Choose how command and tool approvals work. This is the line between usefulness and recklessness.", "اختر طريقة عمل موافقات الأوامر والأدوات. هذا هو الخط الفاصل بين الفائدة والتهور.", [], "security-policy"),
  copy("onboarding.security.title", "Security mode", "وضع الأمان", [], "security-policy"),
  copy("onboarding.security.options.adaptive.label", "Adaptive", "تكيّفي", [], "security-policy"),
  copy("onboarding.security.options.adaptive.description", "Keep human approval at sensitive boundaries.", "أبقِ موافقة الإنسان عند الحدود الحساسة.", [], "security-policy"),
  copy("onboarding.security.options.strict.label", "Strict", "صارم", [], "security-policy"),
  copy("onboarding.security.options.strict.description", "Ask more often before tools and commands.", "اطلب الموافقة أكثر قبل الأدوات والأوامر.", [], "security-policy"),
  copy("onboarding.security.options.open.label", "Open", "مفتوح", [], "security-policy"),
  copy("onboarding.security.options.open.description", "Allow more work without prompts. Review carefully.", "اسمح بمزيد من العمل دون مطالبات. راجع بعناية.", [], "security-policy"),
  copy("onboarding.security.validation.selected", "Choose a security mode.", "اختر وضع الأمان.", [], "security-policy"),
  copy("onboarding.workflowLearning", "Agent Evolution controls how EstaCoda learns reusable skills from your workflow patterns.", "يتحكم تطوّر الوكيل فيما إذا كان بإمكان EstaCoda تعلّم مهارات قابلة لإعادة الاستخدام من أنماط سير عملك.", [], "workflow-learning"),
  copy("onboarding.workflowLearning.title", "Agent Evolution", "تطوّر الوكيل", [], "workflow-learning"),
  copy("onboarding.workflowLearning.options.suggest.label", "Suggest", "اقتراح", [], "workflow-learning"),
  copy("onboarding.workflowLearning.options.suggest.description", "Propose reusable workflow improvements for review.", "اقترح تحسينات قابلة لإعادة الاستخدام لمراجعتها.", [], "workflow-learning"),
  copy("onboarding.workflowLearning.options.none.label", "Off", "إيقاف", [], "workflow-learning"),
  copy("onboarding.workflowLearning.options.none.description", "Do not suggest learned workflow changes.", "لا تقترح تغييرات سير عمل متعلّمة.", [], "workflow-learning"),
  copy("onboarding.workflowLearning.options.proactive.label", "Proactive", "استباقي", [], "workflow-learning"),
  copy("onboarding.workflowLearning.options.proactive.description", "Surface more learning opportunities.", "أظهر فرص تعلّم أكثر.", [], "workflow-learning"),
  copy("onboarding.workflowLearning.options.autonomous.label", "Autonomous", "ذاتي", [], "workflow-learning"),
  copy("onboarding.workflowLearning.options.autonomous.description", "Create stronger workflow suggestions where supported; promotion stays reviewable.", "أنشئ اقتراحات أقوى لسير العمل حيث يكون ذلك مدعومًا؛ تبقى الترقية قابلة للمراجعة.", [], "workflow-learning"),
  copy("onboarding.workflowLearning.validation.selected", "Choose an Agent Evolution mode.", "اختر وضع تطوّر الوكيل.", [], "workflow-learning"),
  copy("onboarding.optionalCapabilities", "Add extra capabilities now, or start light. Skipping them does not weaken core setup.", "أضف القدرات الإضافية الآن، أو ابدأ بتشغيل خفيف. تخطيها لا يضعف الإعداد الأساسي.", [], "optional-capability"),
  copy("onboarding.optionalCapabilities.title", "Optional capabilities", "القدرات الاختيارية", [], "optional-capability"),
  copy("onboarding.optionalCapabilities.configureNow", "Would you like to configure optional capabilities such as Channels, Voice, and Browser now?", "هل ترغب في ضبط قدرات اختيارية مثل القنوات والصوت والمتصفح الآن؟", [], "optional-capability"),
  copy("onboarding.optionalCapabilities.configureNow.yes", "Yes", "نعم", [], "optional-capability"),
  copy("onboarding.optionalCapabilities.configureNow.no", "No", "لا", [], "optional-capability"),
  copy("onboarding.optionalCapabilities.note", "You can configure these capabilities at any time by running estacoda setup.", "يمكنك ضبط هذه القدرات في أي وقت بتشغيل estacoda setup.", [], "optional-capability"),
  copy("onboarding.optionalCapabilities.menu.title", "Configure optional capability", "اضبط قدرة اختيارية", [], "optional-capability"),
  copy("onboarding.optionalCapabilities.more.title", "Configure other capabilities now", "اضبط قدرات أخرى الآن", [], "optional-capability"),
  copy("onboarding.optionalCapabilities.more.yes", "Yes", "نعم", [], "optional-capability"),
  copy("onboarding.optionalCapabilities.skipped", "Optional capabilities skipped. Core setup remains valid.", "تم تخطي القدرات الاختيارية. يظل الإعداد الأساسي صالحًا.", [], "optional-capability"),
  copy("onboarding.optionalCapabilities.promptCapability", "Enable {capabilityId}?", "هل تريد تفعيل {capabilityId}؟", ["{capabilityId}"], "optional-capability"),
  copy("onboarding.optionalCapabilities.enable", "Enable", "تفعيل", [], "optional-capability"),
  copy("onboarding.optionalCapabilities.enableDescription", "Plan {capabilityId} as a reviewed optional capability.", "خطّط {capabilityId} كقدرة اختيارية تخضع للمراجعة.", ["{capabilityId}"], "optional-capability"),
  copy("onboarding.optionalCapabilities.skip", "Skip", "تخطي", [], "optional-capability"),
  copy("onboarding.optionalCapabilities.validation.skippable", "Choose capabilities or skip them safely.", "اختر القدرات أو تخطّها بأمان.", [], "optional-capability"),
  copy("onboarding.summary.confirmTitle", "Configuration summary", "ملخص الإعداد", [], "config-summary"),
  copy("onboarding.summary.confirmMessage", "Confirm these setup choices and apply them.", "أكّد خيارات الإعداد هذه وطبّقها.", [], "config-summary"),
  copy("onboarding.summary.confirmAction", "Confirm", "تأكيد", [], "config-summary"),
  copy("onboarding.summary.cancelAction", "Cancel", "إلغاء", [], "config-summary"),
  copy("onboarding.summary.labels.workspace", "Workspace", "مساحة العمل", [], "config-summary"),
  copy("onboarding.summary.labels.language", "Language", "اللغة", [], "config-summary"),
  copy("onboarding.summary.labels.interfaceStyle", "Interface/style", "أسلوب الواجهة", [], "config-summary"),
  copy("onboarding.summary.labels.activityLabels", "Activity labels", "تسميات النشاط", [], "config-summary"),
  copy("onboarding.summary.labels.primaryProvider", "Primary Provider", "المزوّد الأساسي", [], "config-summary"),
  copy("onboarding.summary.labels.model", "Model", "النموذج", [], "config-summary"),
  copy("onboarding.summary.labels.credentialStatus", "Credential status", "حالة بيانات الاعتماد", [], "config-summary"),
  copy("onboarding.summary.labels.securityMode", "Security Mode", "وضع الأمان", [], "config-summary"),
  copy("onboarding.summary.labels.agentEvolution", "Agent Evolution", "تطوّر الوكيل", [], "config-summary"),
  copy("onboarding.summary.labels.optionalCapabilities", "Optional Capabilities", "القدرات الاختيارية", [], "config-summary"),
  copy("onboarding.summary.labels.channelsTelegram", "Channels / Telegram", "القنوات / Telegram", [], "config-summary"),
  copy("onboarding.summary.labels.voiceStt", "Voice STT", "الصوت STT", [], "config-summary"),
  copy("onboarding.summary.labels.voiceTts", "Voice TTS", "الصوت TTS", [], "config-summary"),
  copy("onboarding.summary.labels.browser", "Browser", "المتصفح", [], "config-summary"),
  copy("onboarding.summary.status.notSet", "Not set", "غير مهيأ", [], "config-summary"),
  copy("onboarding.summary.status.trusted", "trusted", "موثوقة", [], "config-summary"),
  copy("onboarding.summary.status.untrusted", "untrusted", "غير موثوقة", [], "config-summary"),
  copy("onboarding.summary.status.configured", "Configured", "مهيأ", [], "config-summary"),
  copy("onboarding.summary.status.existingCredentialDetected", "Existing credential detected", "تم العثور على بيانات اعتماد موجودة", [], "config-summary"),
  copy("onboarding.summary.status.newCredentialPending", "New credential pending", "بيانات اعتماد جديدة بانتظار الحفظ", [], "config-summary"),
  copy("onboarding.review", "Review exactly what setup would save before approval. Precision beats surprises.", "راجع بالضبط ما سيحفظه الإعداد قبل الموافقة. الدقة أفضل من المفاجآت.", [], "setup-review"),
  copy("onboarding.review.approveAction", "Approve plan", "الموافقة على الخطة", [], "setup-review"),
  copy("onboarding.review.cancelAction", "Cancel", "إلغاء", [], "setup-review"),
  copy("onboarding.review.validation.accepted", "Approve the review or cancel without saving.", "وافق على المراجعة أو ألغِ دون حفظ.", [], "setup-review"),
  copy("setupEditor.review.title", "Finalize configuration", "إنهاء الإعداد", [], "setup-review"),
  copy("setupEditor.review.body", "Confirm selected configuration", "أكّد الإعداد المحدد", [], "setup-review"),
  copy("setupEditor.review.selectedArea", "Selected area: {selectedArea}", "المجال المحدد: {selectedArea}", ["{selectedArea}"], "setup-review"),
  copy("setupEditor.review.confirm", "Confirm", "تأكيد", [], "setup-review"),
  copy("setupEditor.review.confirm.description", "Update your EstaCoda configuration", "حدّث إعدادات EstaCoda", [], "setup-review"),
  copy("setupEditor.review.cancel", "Cancel", "إلغاء", [], "setup-review"),
  copy("setupEditor.review.cancel.description", "Keep your existing configuration unchanged.", "احتفظ بالإعداد الحالي دون تغيير.", [], "setup-review"),
  copy("setupVerification.title", "EstaCoda verify", "فحص EstaCoda", [], "setup-verification"),
  copy("setupVerification.body", "Checks your local setup, provider route, credential store, workspace trust, and basic tool readiness.", "يتحقق من الإعداد المحلي، ومسار المزوّد، ومخزن المفاتيح، وثقة مجلد العمل، وجاهزية الأدوات الأساسية.", [], "setup-verification"),
  copy("setupVerification.stateDirectory", "State directory", "مجلد الحالة", [], "setup-verification"),
  copy("setupVerification.secretStore", "Secret store", "مخزن المفاتيح", [], "setup-verification"),
  copy("setupVerification.workspaceTrust", "Workspace trust", "ثقة مجلد العمل", [], "workspace-trust"),
  copy("setupVerification.securityMode", "Security mode", "وضع الأمان", [], "security-policy"),
  copy("setupVerification.workflowLearning", "Agent Evolution", "تطوّر الوكيل", [], "workflow-learning"),
  copy("setupVerification.readOnlyToolCheck", "Read-only tool check", "فحص أداة القراءة فقط", [], "setup-verification"),
  copy("setupVerification.configSources", "Config sources", "مصادر الإعداد", [], "config-summary"),
  copy("setupVerification.status.writable", "writable", "قابل للكتابة", [], "setup-verification"),
  copy("setupVerification.status.blocked", "blocked", "محظور", [], "setup-verification"),
  copy("setupVerification.status.notPresent", "not present", "غير موجود", [], "setup-verification"),
  copy("setupVerification.status.presentMode", "present ({mode})", "موجود ({mode})", ["{mode}"], "setup-verification"),
  copy("setupVerification.status.skipped", "skipped", "تم التخطي", [], "setup-verification"),
  copy("setupVerification.status.ready", "ready", "جاهز", [], "setup-verification"),
  copy("setupVerification.status.trusted", "trusted", "موثوق", [], "workspace-trust"),
  copy("setupVerification.status.notTrusted", "not trusted", "غير موثوق", [], "workspace-trust"),
  copy("setupVerification.warning.workspaceNotTrusted", "Workspace is not trusted yet; local write/terminal actions will ask first.", "مجلد العمل غير موثوق بعد؛ إجراءات الكتابة والطرفية المحلية ستطلب الموافقة أولاً.", [], "workspace-trust"),
  copy("setupVerification.warning.stateNotWritable", "State directory is not writable.", "مجلد الحالة غير قابل للكتابة.", [], "config-repair"),
  copy("setupVerification.warning.secretMode", "Secret store permissions should be 0600.", "يجب أن تكون صلاحيات مخزن المفاتيح 0600.", [], "credential-reference"),
  copy("setupVerification.warning.readOnlyTool", "Read-only file tool check did not complete.", "لم يكتمل فحص أداة قراءة الملفات.", [], "setup-verification"),
  copy("setupVerification.warning.skippedNoPackageJson", "skipped (no package.json)", "تم التخطي (لا يوجد package.json)", [], "setup-verification"),
  copy("setupVerification.warningsTitle", "Warnings:", "تحذيرات:", [], "setup-verification"),
  copy("setupVerification.nextActionsTitle", "Next actions:", "الخطوات التالية:", [], "setup-verification"),
  copy("setupVerification.statusReady", "Status: ready", "الحالة: جاهز", [], "setup-verification"),
  copy("setupVerification.nextReady", "Next: run estacoda, or configure optional channels with estacoda telegram setup / estacoda browser setup.", "التالي: شغّل estacoda، أو اضبط القنوات الاختيارية عبر estacoda telegram setup / estacoda browser setup.", [], "agent-launch"),
  copy("setupVerification.fallbackNextAction", "Fix the warnings above, then rerun estacoda verify.", "أصلح التحذيرات أعلاه، ثم أعد تشغيل estacoda verify.", [], "setup-verification"),
  copy("setupVerification.actions.providerIncomplete", "Run estacoda setup to choose a provider/model.", "شغّل estacoda setup لاختيار مزوّد ونموذج.", [], "provider-selection"),
  copy("setupVerification.actions.missingApiKey.generic", "Export the missing provider API key, or rerun estacoda setup to store it locally.", "صدّر مفتاح API الناقص، أو أعد تشغيل estacoda setup لحفظه محلياً.", [], "credential-reference"),
  copy("setupVerification.actions.missingApiKey.env", "Export {envVar}, or rerun estacoda setup and choose local secret storage.", "صدّر {envVar}، أو أعد تشغيل estacoda setup واختر تخزين المفتاح محلياً.", ["{envVar}"], "credential-reference"),
  copy("setupVerification.actions.missingCredentialReference", "Run estacoda setup --advanced --provider <provider> --model <model> --api-key-env <ENV_NAME>.", "شغّل estacoda setup --advanced --provider <provider> --model <model> --api-key-env <ENV_NAME>.", [], "credential-reference"),
  copy("setupVerification.actions.networkDisabled", "Enable network inference for the selected hosted provider with estacoda setup --advanced.", "فعّل الاستدلال عبر الشبكة للمزوّد المستضاف المختار باستخدام estacoda setup --advanced.", [], "provider-selection"),
  copy("setupVerification.actions.workspaceNotTrusted", "Run /workspace.trust.grant in an interactive session, or rerun estacoda setup and trust this workspace.", "شغّل /workspace.trust.grant داخل جلسة تفاعلية، أو أعد تشغيل estacoda setup ومنح الثقة لهذا المجلد.", [], "workspace-trust"),
  copy("setupVerification.actions.secretPermissions", "Restrict the local secret-store file to mode 0600, then rerun estacoda verify.", "قيّد ملف مخزن المفاتيح المحلي إلى الوضع 0600، ثم أعد تشغيل estacoda verify.", [], "credential-reference"),
  copy("setupVerification.actions.stateNotWritable", "Check write permissions for ~/.estacoda.", "تحقق من صلاحيات الكتابة في ~/.estacoda.", [], "config-repair"),
  copy("setupVerification.actions.readOnlyTool", "Start an interactive session after fixing provider/trust warnings, then retry estacoda verify.", "ابدأ جلسة تفاعلية بعد إصلاح تحذيرات المزوّد/الثقة، ثم أعد تشغيل estacoda verify.", [], "setup-verification"),
  copy("onboarding.launch.startNow", "Start EstaCoda now?", "هل تريد تشغيل EstaCoda الآن؟", [], "agent-launch"),
  copy("onboarding.launch.startNow.yes", "Yes", "نعم", [], "agent-launch"),
  copy("onboarding.launch.startNow.no", "No", "لا", [], "agent-launch"),

  copy("setupRouter.firstRun.title", "First-run setup", "إعداد أول تشغيل", [], "none"),
  copy("setupRouter.firstRun.summary", "No usable setup config was found. Start first-run setup and review changes before applying them.", "لم يتم العثور على إعداد صالح. ابدأ إعداد أول تشغيل، وراجع التغييرات قبل تطبيقها.", [], "setup-review"),
  copy("setupRouter.configured.title", "EstaCoda is already configured", "تم إعداد EstaCoda بالفعل", [], "config-summary"),
  copy("setupRouter.configured.summary", "Setup looks ready. Launch EstaCoda, review setup, run read-only verification, or exit.", "يبدو الإعداد جاهزًا. شغّل EstaCoda، أو راجع الإعداد، أو شغّل تحققًا للقراءة فقط، أو اخرج.", [], "config-summary"),
  copy("setupRouter.degraded.title", "EstaCoda is configured with warnings", "تم إعداد EstaCoda مع وجود تحذيرات", [], "config-summary"),
  copy("setupRouter.degraded.summary", "Setup is usable with warnings. Review the warnings, repair setup, or continue in limited mode.", "الإعداد قابل للاستخدام مع تحذيرات. راجع التحذيرات، أو أصلح الإعداد، أو تابع في الوضع المحدود.", [], "config-summary"),
  copy("setupRouter.repair.title", "Setup needs repair", "الإعداد يحتاج إلى إصلاح", [], "config-repair"),
  copy("setupRoute.action.launchAgent", "Launch after verification", "شغّل بعد التحقق", [], "agent-launch"),
  copy("setupRoute.action.acceptLimitedMode", "Accept limited mode after reviewing warnings", "اقبل الوضع المحدود بعد مراجعة التحذيرات", [], "agent-launch"),
  copy("setupRoute.action.verifySetup", "Run read-only verification", "شغّل تحققًا للقراءة فقط", [], "setup-verification"),
  copy("setupRoute.action.exit", "Exit without changes", "اخرج دون تغييرات", [], "none"),

  copy("setupStateSummary.title", "EstaCoda setup", "إعداد EstaCoda", [], "config-summary"),
  copy("setupStateSummary.advancedTitle", "EstaCoda advanced setup", "إعداد EstaCoda المتقدم", [], "config-summary"),
  copy("setupStateSummary.directProviderExample", "Direct provider example: `estacoda setup --provider deepseek --model deepseek-chat --api-key-env DEEPSEEK_API_KEY`", "مثال إعداد مزوّد مباشر: `estacoda setup --provider deepseek --model deepseek-chat --api-key-env DEEPSEEK_API_KEY`", [], "provider-selection"),

  copy("setupEditor.shell.title", "Setup Editor", "محرّر الإعدادات", [], "config-summary"),
  copy("setupEditor.shell.labels.state", "State", "الحالة", [], "config-summary"),
  copy("setupEditor.shell.labels.kind", "Kind", "النوع", [], "config-summary"),
  copy("setupEditor.shell.labels.route", "Setup path", "مسار الإعداد", [], "config-summary"),
  copy("setupEditor.shell.labels.editorMode", "Editor mode", "وضع المحرر", [], "config-summary"),
  copy("setupEditor.shell.labels.recommended", "Recommended action", "الإجراء المقترح", [], "config-summary"),
  copy("setupEditor.shell.labels.model", "Model", "النموذج", [], "provider-selection"),
  copy("setupEditor.shell.labels.userConfig", "Configuration", "الإعدادات", [], "config-summary"),
  copy("setupEditor.shell.labels.projectConfig", "Workspace trust", "ثقة مساحة العمل", [], "config-summary"),
  copy("setupEditor.shell.labels.stateWritable", "State writable", "الحالة قابلة للكتابة", [], "config-summary"),
  copy("setupEditor.shell.labels.blockers", "Blockers", "العوائق", [], "config-repair"),
  copy("setupEditor.shell.labels.warnings", "Warnings", "التحذيرات", [], "config-repair"),
  copy("setupEditor.shell.labels.status", "status", "الحالة", [], "config-summary"),
  copy("setupEditor.shell.labels.blocker", "blocker", "عائق", [], "config-repair"),
  copy("setupEditor.shell.labels.warning", "warning", "تحذير", [], "config-repair"),
  copy("setupEditor.shell.labels.none", "none", "لا شيء", [], "config-summary"),
  copy("setupEditor.shell.values.yes", "yes", "نعم", [], "config-summary"),
  copy("setupEditor.shell.values.no", "no", "لا", [], "config-summary"),
  copy("setupEditor.sections.heading", "Sections", "الأقسام", [], "config-summary"),
  copy("setupEditor.actions.heading", "Available actions", "الإجراءات المتاحة", [], "config-summary"),

  copy("setupEditor.summary.configuredReady", "Setup is configured and ready. Review or change the parts worth checking.", "الإعداد مهيأ وجاهز. راجع أو عدّل الأجزاء التي تستحق التدقيق.", [], "config-summary"),
  copy("setupEditor.summary.configuredDegraded", "Setup works with warnings. Review warnings before launch.", "الإعداد يعمل مع تحذيرات. راجع التحذيرات قبل التشغيل.", [], "config-summary"),
  copy("setupEditor.summary.repairFirst", "Repair required setup items before normal editing. No polishing helps a setup that does not work.", "يجب إصلاح عناصر الإعداد المطلوبة قبل التحرير العادي. لا جدوى من تلميع إعداد لا يعمل.", [], "config-repair"),
  copy("setupEditor.sections.configSummary", "Current setup sources and readiness.", "مصادر الإعداد الحالية وحالة الجاهزية.", [], "config-summary"),
  copy("setupEditor.sections.configSafety", "Config cannot be edited normally until it can be parsed safely.", "لا يمكن تحرير الإعدادات بشكل عادي حتى يمكن قراءتها بأمان.", [], "config-repair"),
  copy("setupEditor.sections.stateSafety", "State/config path is not writable. Normal writes are blocked until state write permissions are restored.", "مسار الحالة/الإعداد غير قابل للكتابة. الكتابة العادية محظورة حتى تُستعاد أذونات كتابة الحالة.", [], "config-repair"),
  copy("setupEditor.sections.modelRoute", "Primary provider and model.", "المزوّد والنموذج الأساسي.", [], "provider-selection"),
  copy("setupEditor.sections.credentials", "Credential references and secret-store status. Secret values stay hidden.", "مراجع بيانات الاعتماد وحالة مخزن الأسرار. تبقى قيم الأسرار مخفية.", [], "credential-reference"),
  copy("setupEditor.sections.securityMode", "Command and tool approval mode.", "وضع موافقات الأوامر والأدوات.", [], "security-policy"),
  copy("setupEditor.sections.workflowLearning", "Agent Evolution mode.", "وضع تطوّر الوكيل.", [], "workflow-learning"),
  copy("setupEditor.sections.interfacePreference", "Language and interface preferences.", "تفضيلات اللغة والواجهة.", [], "interface-preference"),
  copy("setupEditor.sections.workspaceTrust", "Workspace trust status. Trust is separate from model readiness.", "حالة ثقة مساحة العمل. الثقة منفصلة عن جاهزية النموذج.", [], "workspace-trust"),
  copy("setupEditor.sections.optionalCapabilities", "Optional capabilities are reviewed independently. Add-ons do not enter core setup through the back door.", "تتم مراجعة القدرات الاختيارية بشكل مستقل. الإضافات لا تدخل الإعداد الأساسي من الباب الخلفي.", [], "optional-capability"),
  copy("setupEditor.sections.verification", "Run read-only verification.", "شغّل تحققًا للقراءة فقط.", [], "setup-verification"),
  copy("setupEditor.sections.exit", "Exit setup without applying changes.", "اخرج من الإعداد دون تطبيق تغييرات.", [], "none"),
  copy("setupEditor.actions.editPrimaryModelRoute", "Edit primary model", "عدّل النموذج الأساسي", [], "provider-selection"),
  copy("setupEditor.actions.repairPrimaryProvider", "Repair primary provider/model setup.", "أصلح إعداد المزوّد/النموذج الأساسي.", [], "provider-selection"),
  copy("setupEditor.actions.editPrimaryCredentialReference", "Edit credential environment variable reference.", "عدّل مرجع متغير البيئة لبيانات الاعتماد.", [], "credential-reference"),
  copy("setupEditor.actions.storeProviderCredentialReference", "Store provider credential reference.", "احفظ مرجع بيانات اعتماد المزوّد.", [], "credential-reference"),
  copy("setupEditor.actions.editFallbackModelRoute", "Edit fallback models", "عدّل النماذج الاحتياطية", [], "provider-selection"),
  copy("setupEditor.actions.editAuxiliaryModelRoute", "Edit auxiliary models", "عدّل النماذج المساندة", [], "provider-selection"),
  copy("setupEditor.actions.repairMissingCredential", "Repair missing credential reference {envVar}.", "أصلح مرجع بيانات الاعتماد المفقود {envVar}.", ["{envVar}"], "credential-reference"),
  copy("setupEditor.actions.editSecurityMode", "Edit security mode", "عدّل وضع الأمان", [], "security-policy"),
  copy("setupEditor.actions.editWorkflowLearning", "Configure Agent Evolution", "عدّل تطوّر الوكيل", [], "workflow-learning"),
  copy("setupEditor.actions.chooseLanguage", "Choose language", "اختار اللغة", [], "interface-preference"),
  copy("setupEditor.actions.repairWorkspaceTrust", "Review workspace trust grant for {workspacePath}.", "راجع منح الثقة لمساحة العمل {workspacePath}.", ["{workspacePath}"], "workspace-trust"),
  copy("setupEditor.actions.configureChannels", "Configure channels", "اضبط القنوات", [], "optional-capability"),
  copy("setupEditor.actions.configureVoice", "Configure voice", "اضبط الصوت", [], "optional-capability"),
  copy("setupEditor.actions.configureImageGeneration", "Configure image generation", "اضبط توليد الصور", [], "optional-capability"),
  copy("setupEditor.actions.configureBrowser", "Configure browser", "اضبط المتصفح", [], "optional-capability"),
  copy("setupEditor.actions.runReadonlyVerification", "Run setup verification", "شغّل فحص الإعداد", [], "setup-verification"),
  copy("setupEditor.actions.showDiagnostics", "Show diagnostics", "اعرض التشخيصات", [], "config-repair"),
  copy("setupEditor.actions.exitWithoutChanges", "Exit without changes", "اخرج بدون تغييرات", [], "none"),
  copy("setupEditor.actions.repairBrokenConfig", "Inspect broken config before normal editing.", "افحص ملف الإعداد المعطّل قبل التحرير العادي.", [], "config-repair"),
  copy("setupEditor.actions.repairStateDirectory", "Repair state directory permissions.", "أصلح أذونات مجلد الحالة.", [], "config-repair"),
  copy("setupEditor.actions.cancelSetupEditor", "Exit without changes", "اخرج بدون تغييرات", [], "none"),
  copy("setupEditor.actions.repairWorkspaceTrust.description", "Review and approve workspace trust before local write or terminal actions are allowed.", "راجع ووافق على ثقة مساحة العمل قبل السماح بإجراءات الكتابة المحلية أو الطرفية.", [], "workspace-trust"),
  copy("setupEditor.actions.editSecurityMode.description", "Choose how strictly EstaCoda reviews risky actions.", "اختار مدى صرامة EstaCoda في مراجعة الإجراءات الحساسة.", [], "security-policy"),
  copy("setupEditor.actions.editWorkflowLearning.description", "Agent Evolution controls how EstaCoda learns reusable skills from your workflow patterns.", "يسمح هذا الخيار لـ EstaCoda بتعلّم مهارات قابلة لإعادة الاستخدام من الأنماط المتكررة في عملك.", [], "workflow-learning"),
  copy("setupEditor.actions.chooseLanguage.description", "Choose English or Arabic. Arabic support is beta and may fall back to English.", "اختار الإنجليزية أو العربية. دعم العربية ما زال تجريبي وقد يرجع للإنجليزية أحيانًا.", [], "interface-preference"),
  copy("setupEditor.actions.repairPrimaryProvider.description", "Repair the primary provider and model through the shared setup flow.", "أصلح المزوّد والنموذج الأساسي عبر إعداد مشترك.", [], "provider-selection"),
  copy("setupEditor.actions.editPrimaryModelRoute.description", "Set the default provider and model used by the agent.", "حدّد المزوّد والنموذج اللي يستخدمه الوكيل.", [], "provider-selection"),
  copy("setupEditor.actions.repairMissingCredential.description", "Repair the missing credential for the current active model.", "أصلح بيانات الاعتماد الناقصة للنموذج النشط الحالي.", [], "credential-reference"),
  copy("setupEditor.actions.editPrimaryCredentialReference.description", "Update the credential reference for the current active model.", "حدّث مرجع بيانات الاعتماد للنموذج النشط الحالي.", [], "credential-reference"),
  copy("setupEditor.actions.storeProviderCredentialReference.description", "Store the provider credential reference without exposing the secret value.", "احفظ مرجع بيانات اعتماد المزوّد دون كشف قيمة السر.", [], "credential-reference"),
  copy("setupEditor.actions.editFallbackModelRoute.description", "Configure backup providers and models used when the primary model fails.", "اضبط المزوّدين والنماذج الاحتياطية المستخدمة لو تعثّر النموذج الأساسي.", [], "provider-selection"),
  copy("setupEditor.actions.editAuxiliaryModelRoute.description", "Configure specialist models for assessment, compression, recall, and memory.", "اضبط النماذج المتخصصة للتقييم، الضغط، الاسترجاع، والذاكرة.", [], "provider-selection"),
  copy("setupEditor.actions.configureChannels.description", "Set up remote-control channels such as Telegram.", "فعّل قنوات التحكم عن بُعد مثل Telegram.", [], "optional-capability"),
  copy("setupEditor.actions.configureVoice.description", "Set speech-to-text and text-to-speech providers.", "حدّد مزوّدي تحويل الكلام إلى نص والنص إلى كلام.", [], "optional-capability"),
  copy("setupEditor.actions.configureImageGeneration.description", "Set the image generation provider.", "حدّد مزوّد توليد الصور.", [], "optional-capability"),
  copy("setupEditor.actions.configureBrowser.description", "Set browser behavior without launching a browser.", "اضبط سلوك المتصفح من غير ما تشغّل متصفح.", [], "optional-capability"),
  copy("setupEditor.actions.runReadonlyVerification.description", "Check setup state without changing config.", "افحص حالة الإعداد من غير تغيير ملف الإعدادات.", [], "setup-verification"),
  copy("setupEditor.actions.showDiagnostics.description", "List blockers, warnings, and detected state.", "اعرض العوائق، التحذيرات، والحالة المكتشفة.", [], "config-repair"),
  copy("setupEditor.actions.exitWithoutChanges.description", "Leave setup without modifying config.", "اخرج من الإعداد من غير تعديل أي شيء.", [], "none"),
  copy("setupEditor.result.unsupportedState", "Setup editor is available only for configured, degraded, or repair setup states.", "محرّر الإعدادات متاح فقط لحالات الإعداد الجاهزة، أو المتراجعة، أو التي تحتاج إصلاحًا.", [], "config-repair"),
  copy("setupEditor.result.noActions", "No setup editor actions are available.", "لا توجد إجراءات متاحة في محرّر الإعدادات.", [], "config-summary"),
  copy("setupEditor.result.unavailableAction", "Action {actionId} is not available in the setup editor.", "الإجراء {actionId} غير متاح في محرّر الإعدادات.", ["{actionId}"], "config-summary"),
  copy("setupEditor.result.unimplementedAction", "Action {actionId} is not implemented in the setup editor.", "الإجراء {actionId} غير منفّذ في محرّر الإعدادات.", ["{actionId}"], "config-summary"),
  copy("setupEditor.result.verifyPrepared", "Setup verification prepared.", "تم تجهيز فحص الإعداد.", [], "setup-verification"),
  copy("setupEditor.result.exitWithoutChanges", "Exited setup editor without applying changes.", "تم الخروج من محرّر الإعدادات من غير تطبيق تغييرات.", [], "none"),
  copy("setupEditor.result.repairAgainSelected", "Repair again selected. Re-entering setup editor.", "تم اختيار الإصلاح مرة أخرى. جارٍ الرجوع إلى محرّر الإعدادات.", [], "config-repair"),
  copy("setupEditor.result.activeModelMissing", "No active provider/model is configured. Use provider/model repair to choose a setup-visible model.", "لا يوجد مزوّد/نموذج نشط مهيأ. استخدم إصلاح المزوّد/النموذج لاختيار نموذج ظاهر في الإعداد.", [], "provider-selection"),
  copy("setupEditor.result.activeModelUnavailable", "The active provider/model {providerId}/{modelId} is not available for credential repair. Use provider/model repair to choose a setup-visible model.", "المزوّد/النموذج النشط {providerId}/{modelId} غير متاح لإصلاح بيانات الاعتماد. استخدم إصلاح المزوّد/النموذج لاختيار نموذج ظاهر في الإعداد.", ["{providerId}", "{modelId}"], "provider-selection"),
  copy("setupEditor.result.activeModelCredentialUnsupported", "The active provider/model {providerId}/{modelId} cannot be repaired through credential-only setup: {reason}. Use provider/model repair to choose a setup-visible model.", "لا يمكن إصلاح المزوّد/النموذج النشط {providerId}/{modelId} عبر إعداد بيانات الاعتماد فقط: {reason}. استخدم إصلاح المزوّد/النموذج لاختيار نموذج ظاهر في الإعداد.", ["{providerId}", "{modelId}", "{reason}"], "provider-selection"),
  copy("setupEditor.diagnostics.title", "Setup diagnostics", "تشخيص الإعداد", [], "config-repair"),
  copy("setupEditor.diagnostics.labels.error", "Error", "الخطأ", [], "config-repair"),
  copy("setupEditor.diagnostics.manualRepair.heading", "Manual repair guidance", "إرشادات الإصلاح اليدوي", [], "config-repair"),
  copy("setupEditor.diagnostics.manualRepair.brokenConfig", "Normal config edits are blocked until the config file can be parsed. Fix the listed parse/load error, then run read-only verification again.", "تعديلات الإعداد العادية محظورة حتى يمكن قراءة ملف الإعداد. أصلح خطأ القراءة/التحميل المعروض، ثم شغّل التحقق للقراءة فقط مرة أخرى.", [], "config-repair"),
  copy("setupEditor.diagnostics.manualRepair.stateNotWritable", "Normal writes are blocked until the state/config path is writable. Restore write permission, then run read-only verification again.", "الكتابة العادية محظورة حتى يصبح مسار الحالة/الإعداد قابلًا للكتابة. أعد أذونات الكتابة، ثم شغّل التحقق للقراءة فقط مرة أخرى.", [], "config-repair"),
  copy("setupEditor.diagnostics.manualRepair.availableActions", "Only diagnostics, verification, and exit are available from this state.", "لا تتوفر من هذه الحالة إلا التشخيصات، الفحص، والخروج.", [], "config-repair"),
  copy("setupEditor.prompt.action.title", "Setup editor", "محرّر الإعدادات", [], "config-summary"),
  copy("setupEditor.prompt.action.body", "Choose what to configure.", "اختار اللي تحب تضبطه.", [], "config-summary"),
  copy("setupEditor.prompt.postApply.title", "Setup next action", "الإجراء التالي للإعداد", [], "agent-launch"),
  copy("setupEditor.prompt.postApply.body", "Choose what happens next. Launch only after setup is verified ready; continue in limited mode only after reviewing warnings.", "اختر ما يحدث بعد ذلك. لا يتم التشغيل إلا بعد التحقق من الجاهزية؛ ولا تتابع في الوضع المحدود إلا بعد مراجعة التحذيرات.", [], "agent-launch"),
  copy("setupEditor.prompt.postApply.launch", "Launch EstaCoda", "شغّل EstaCoda", [], "agent-launch"),
  copy("setupEditor.prompt.postApply.launch.description", "Start the interactive session after verified-ready setup.", "ابدأ الجلسة التفاعلية بعد تأكيد جاهزية الإعداد.", [], "agent-launch"),
  copy("setupEditor.prompt.postApply.acceptLimitedMode", "Continue in limited mode", "تابع في الوضع المحدود", [], "agent-launch"),
  copy("setupEditor.prompt.postApply.acceptLimitedMode.description", "Launch with the verified warnings shown above.", "شغّل مع التحذيرات المؤكدة المعروضة أعلاه.", [], "agent-launch"),
  copy("setupEditor.prompt.postApply.repairAgain", "Repair again", "أصلح مرة أخرى", [], "config-repair"),
  copy("setupEditor.prompt.postApply.repairAgain.description", "Re-check setup and return to the setup editor.", "أعد فحص الإعداد وارجع إلى محرّر الإعدادات.", [], "config-repair"),
  copy("setupEditor.prompt.postApply.exit", "Exit setup", "اخرج من الإعداد", [], "none"),
  copy("setupEditor.prompt.postApply.exit.description", "Leave setup without launching.", "اخرج من الإعداد من غير تشغيل.", [], "none"),
  copy("setupEditor.postApply.warningList", "Verification warnings", "تحذيرات التحقق", [], "setup-verification"),
  copy("setupEditor.prompt.credentialReuse.title", "Saved provider API key", "مفتاح API محفوظ للمزوّد", [], "credential-reference"),
  copy("setupEditor.prompt.credentialReuse.body", "Choose how to handle the saved credential reference.", "اختر كيفية التعامل مع مرجع بيانات الاعتماد المحفوظ.", [], "credential-reference"),
  copy("setupEditor.prompt.credentialReuse.existing", "Use existing saved API key.", "استخدم مفتاح API المحفوظ الحالي.", [], "credential-reference"),
  copy("setupEditor.prompt.credentialReuse.existing.description", "Keep the saved credential reference and continue.", "احتفظ بمرجع بيانات الاعتماد المحفوظ وتابع.", [], "credential-reference"),
  copy("setupEditor.prompt.credentialReuse.new", "Enter a new API key.", "أدخل مفتاح API جديدًا.", [], "credential-reference"),
  copy("setupEditor.prompt.credentialReuse.new.description", "Replace the saved secret value after review.", "استبدل قيمة السر المحفوظة بعد المراجعة.", [], "credential-reference"),
  copy("setupEditor.prompt.fallbackRoute.title", "Fallback models", "النماذج الاحتياطية", [], "provider-selection"),
  copy("setupEditor.prompt.fallbackRoute.body", "Choose an existing fallback model to replace, or add another fallback model.", "اختر نموذجًا احتياطيًا موجودًا لاستبداله، أو أضف نموذجًا احتياطيًا آخر.", [], "provider-selection"),
  copy("setupEditor.prompt.fallbackRoute.edit", "Edit fallback {index}: {providerId}/{modelId}", "عدّل الاحتياطي {index}: {providerId}/{modelId}", ["{index}", "{providerId}", "{modelId}"], "provider-selection"),
  copy("setupEditor.prompt.fallbackRoute.edit.description", "Replace this fallback provider/model after review.", "استبدل مزوّد/نموذج الاحتياطي هذا بعد المراجعة.", [], "provider-selection"),
  copy("setupEditor.prompt.fallbackRoute.add", "Add another fallback model", "أضف نموذجًا احتياطيًا آخر", [], "provider-selection"),
  copy("setupEditor.prompt.fallbackRoute.add.description", "Append a new backup provider/model after the existing fallbacks.", "أضف مزوّد/نموذج احتياطيًا جديدًا بعد الاحتياطيات الحالية.", [], "provider-selection"),
  copy("setupEditor.prompt.auxiliaryRoute.title", "Choose auxiliary model.", "اختر نموذجًا مساعدًا.", [], "provider-selection"),
  copy("setupEditor.prompt.auxiliaryRoute.body", "Choose the specialist task to configure through a reviewed setup change.", "اختر المهمة المتخصصة التي تريد ضبطها عبر تغيير إعداد تتم مراجعته.", [], "provider-selection"),
  copy("setupEditor.prompt.auxiliaryRoute.assessor", "Assessor", "المقيّم", [], "provider-selection"),
  copy("setupEditor.prompt.auxiliaryRoute.assessor.description", "Configure assessor for approval assessment through reviewed setup.", "اضبط assessor لتقييم الموافقات عبر إعداد تتم مراجعته.", [], "provider-selection"),
  copy("setupEditor.prompt.auxiliaryRoute.compression", "Compression", "الضغط", [], "provider-selection"),
  copy("setupEditor.prompt.auxiliaryRoute.compression.description", "Configure compression summarization.", "اضبط تلخيص compression.", [], "provider-selection"),
  copy("setupEditor.prompt.auxiliaryRoute.sessionSearch", "Session search", "بحث الجلسات", [], "provider-selection"),
  copy("setupEditor.prompt.auxiliaryRoute.sessionSearch.description", "Configure session_search.", "اضبط session_search.", [], "provider-selection"),
  copy("setupEditor.prompt.auxiliaryRoute.memoryCompaction", "Memory compaction", "ضغط الذاكرة", [], "provider-selection"),
  copy("setupEditor.prompt.auxiliaryRoute.memoryCompaction.description", "Configure memory_compaction.", "اضبط memory_compaction.", [], "provider-selection"),
  copy("setupEditor.prompt.auxiliaryRoute.profileContext", "Profile context", "سياق الملف الشخصي", [], "provider-selection"),
  copy("setupEditor.prompt.auxiliaryRoute.profileContext.description", "Configure profile_context.", "اضبط profile_context.", [], "provider-selection"),
  copy("setupEditor.prompt.optionalCapabilityAction.leaveUnchanged", "Leave unchanged", "اتركه كما هو", [], "optional-capability"),
  copy("setupEditor.prompt.optionalCapabilityAction.skip", "Skip", "تخطَّ", [], "optional-capability"),
  copy("setupEditor.prompt.optionalCapabilityAction.enableConfigure", "Enable/configure", "فعّل/اضبط", [], "optional-capability"),
  copy("setupEditor.prompt.optionalCapabilityAction.leaveUnchanged.description", "Keep the current setting and write nothing.", "احتفظ بالإعداد الحالي دون كتابة أي تغيير.", [], "optional-capability"),
  copy("setupEditor.prompt.optionalCapabilityAction.skip.description", "Skip this optional capability. Core setup remains valid.", "تخطَّ هذه القدرة الاختيارية. يبقى الإعداد الأساسي صالحًا.", [], "optional-capability"),
  copy("setupEditor.prompt.optionalCapabilityAction.enableConfigure.description", "Review and configure this optional capability.", "راجع واضبط هذه القدرة الاختيارية.", [], "optional-capability"),
  copy("setupEditor.prompt.channels.title", "Choose channel", "اختر القناة", [], "optional-capability"),
  copy("setupEditor.prompt.channels.body", "Choose which remote-control channel to configure.", "اختر قناة التحكم عن بُعد التي تريد ضبطها.", [], "optional-capability"),
  copy("setupEditor.prompt.channels.telegram", "Telegram", "Telegram", [], "optional-capability"),
  copy("setupEditor.prompt.channels.telegram.description", "Configure Telegram for private and group chats", "اضبط Telegram للمحادثات الخاصة ومحادثات المجموعات", [], "optional-capability"),
  copy("setupEditor.prompt.channels.whatsapp", "WhatsApp beta", "WhatsApp تجريبي", [], "optional-capability"),
  copy("setupEditor.prompt.channels.whatsapp.description", "Configure WhatsApp beta with an explicit allowed-user list.", "اضبط WhatsApp التجريبي مع قائمة مستخدمين مسموح بها بوضوح.", [], "optional-capability"),
  copy("setupEditor.prompt.channels.discord", "Discord beta", "Discord تجريبي", [], "optional-capability"),
  copy("setupEditor.prompt.channels.discord.description", "Configure Discord beta with explicit allowed users or channels.", "اضبط Discord التجريبي مع مستخدمين أو قنوات مسموح بها بوضوح.", [], "optional-capability"),
  copy(
    "setupEditor.prompt.telegram.summary",
    "Telegram gives EstaCoda a remote command channel. Set the bot token, then restrict access to the users or chats you actually trust.",
    "يمنح Telegram لـ EstaCoda قناة أوامر عن بُعد. اضبط رمز البوت، ثم قيّد الوصول بالمستخدمين أو المحادثات التي تثق بها فعليًا.",
    [],
    "optional-capability"
  ),
  copy("setupEditor.prompt.telegram.card.title", "Configure Telegram", "ضبط Telegram", [], "optional-capability"),
  copy("setupEditor.prompt.telegram.botToken.heading", "Connect Telegram bot", "ربط بوت Telegram", [], "optional-capability"),
  copy(
    "setupEditor.prompt.telegram.botToken.body",
    "EstaCoda can receive commands from Telegram once you connect a bot. Follow the steps below:\n1. Open Telegram and search for the official @BotFather account. Use the verified account with the blue checkmark.\n2. Send /newbot and follow BotFather’s instructions to create a bot if you do not already have one.\n3. Copy the API token BotFather gives you.\n4. Paste the API token below.",
    "يمكن لـ EstaCoda تلقّي الأوامر من Telegram بعد ربط بوت. اتبع الخطوات التالية:\n\n1. افتح Telegram وابحث عن الحساب الرسمي @BotFather. استخدم الحساب الموثّق بعلامة التحقق الزرقاء.\n2. أرسل الأمر /newbot واتبع تعليمات BotFather لإنشاء بوت إذا لم يكن لديك بوت بالفعل.\n3. انسخ رمز API الذي يرسله لك BotFather.\n4. الصق رمز API أدناه:",
    [],
    "optional-capability"
  ),
  copy("setupEditor.prompt.telegram.botToken", "Telegram bot API token:", "رمز API الخاص ببوت Telegram", [], "optional-capability"),
  copy("setupEditor.prompt.telegram.allowedUserIds.heading", "Authorize Telegram users", "اعتماد مستخدمي Telegram", [], "optional-capability"),
  copy(
    "setupEditor.prompt.telegram.allowedUserIds.body",
    "EstaCoda will only accept Telegram commands from approved Telegram user IDs. Follow the steps below:\n\n1. Open Telegram and search for @userinfobot.\n2. Send /start to get your Telegram user ID.\n3. Repeat this for any other Telegram account that should control EstaCoda.\n4. Enter one or more user IDs below. Use commas to separate multiple IDs.",
    "لن يقبل EstaCoda أوامر Telegram إلا من معرّفات المستخدمين المعتمدة. اتبع الخطوات التالية:\n\n1. افتح Telegram وابحث عن @userinfobot.\n2. أرسل الأمر /start للحصول على معرّف مستخدم Telegram الخاص بك.\n3. كرّر هذه الخطوة لأي حساب Telegram آخر يجب أن يتحكم في EstaCoda.\n4. أدخل معرّف مستخدم واحدًا أو أكثر أدناه. استخدم الفواصل للفصل بين عدة معرّفات.",
    [],
    "optional-capability"
  ),
  copy("setupEditor.prompt.telegram.allowedUserIds", "Allowed Telegram user ID(s):", "معرّف/معرّفات مستخدم Telegram المسموح بها:", [], "optional-capability"),
  copy("setupEditor.prompt.telegram.allowedChatIds.heading", "Authorize Telegram group chats", "اعتماد محادثات مجموعات Telegram", [], "optional-capability"),
  copy(
    "setupEditor.prompt.telegram.allowedChatIds.body",
    "EstaCoda will only accept Telegram commands from approved group chat IDs. Follow the steps below:\n\n1. Open Telegram and create a new group chat, or use an existing group chat.\n2. Add your EstaCoda Telegram bot to the group chat.\n3. Add @getidsbot or @chatIDrobot to the same group chat.\n4. The ID bot will reply with the group chat ID. For groups, this is usually a long negative number.\n5. Enter one or more chat IDs below. Use commas to separate multiple IDs.",
    "لن يقبل EstaCoda أوامر Telegram إلا من معرّفات محادثات المجموعات المعتمدة. اتبع الخطوات التالية:\n\n1. افتح Telegram وأنشئ محادثة مجموعة جديدة، أو استخدم محادثة مجموعة موجودة.\n2. أضف بوت Telegram الخاص بـ EstaCoda إلى محادثة المجموعة.\n3. أضف @getidsbot أو @chatIDrobot إلى محادثة المجموعة نفسها.\n4. سيرد بوت المعرّفات بمعرّف محادثة المجموعة. في المجموعات، يكون هذا عادةً رقمًا سالبًا طويلًا.\n5. أدخل معرّف محادثة واحدًا أو أكثر أدناه. استخدم الفواصل للفصل بين عدة معرّفات.",
    [],
    "optional-capability"
  ),
  copy("setupEditor.prompt.telegram.allowedChatIds", "Allowed Telegram group chat ID(s):", "معرّف/معرّفات محادثات مجموعات Telegram", [], "optional-capability"),
  copy("setupEditor.prompt.telegram.remoteControlRisk", "Remote-control access must be restricted before Telegram can be enabled.", "يجب تقييد الوصول للتحكم عن بُعد قبل تفعيل Telegram.", [], "optional-capability"),
  copy("setupEditor.prompt.telegram.incomplete.body", "Add at least one allowed user or chat ID, or skip Telegram for now.", "أضف معرّف مستخدم أو محادثة واحدًا على الأقل، أو تخطَّ Telegram الآن.", [], "optional-capability"),
  copy("setupEditor.prompt.telegram.incomplete.retry", "Add allowed identities", "أضف الهويات المسموح بها", [], "optional-capability"),
  copy("setupEditor.prompt.telegram.incomplete.retry.description", "Return to Telegram fields and add an allowed user or chat ID.", "ارجع إلى حقول Telegram وأضف معرّف مستخدم أو محادثة مسموحًا به.", [], "optional-capability"),
  copy("setupEditor.prompt.discord.summary", "Discord beta remote control needs a bot token reference and an explicit allowlist.", "التحكم عن بُعد عبر Discord التجريبي يحتاج مرجع رمز البوت وقائمة سماح واضحة.", [], "optional-capability"),
  copy("setupEditor.prompt.discord.beta", "Discord support is beta. Keep access limited to known users or channels.", "دعم Discord تجريبي. اجعل الوصول محصورًا في مستخدمين أو قنوات معروفة.", [], "optional-capability"),
  copy("setupEditor.prompt.discord.remoteControlRisk", "Discord can remotely control EstaCoda, so setup fails closed without an allowlist.", "يمكن لـ Discord التحكم في EstaCoda عن بُعد، لذلك يفشل الإعداد بأمان من غير قائمة سماح.", [], "optional-capability"),
  copy("setupEditor.prompt.discord.botTokenEnv", "Discord bot token environment variable", "اسم متغير البيئة لرمز بوت Discord", [], "optional-capability"),
  copy("setupEditor.prompt.discord.botToken", "Discord bot token (leave blank to use an existing env var)", "رمز بوت Discord (اتركه فارغًا لاستخدام متغير بيئة موجود)", [], "optional-capability"),
  copy("setupEditor.prompt.discord.allowedUsers", "Allowed Discord user IDs", "معرّفات مستخدمي Discord المسموح بها", [], "optional-capability"),
  copy("setupEditor.prompt.discord.allowedGuilds", "Allowed Discord guild IDs", "معرّفات خوادم Discord المسموح بها", [], "optional-capability"),
  copy("setupEditor.prompt.discord.allowedChannels", "Allowed Discord channel IDs", "معرّفات قنوات Discord المسموح بها", [], "optional-capability"),
  copy("setupEditor.prompt.discord.incomplete.body", "Discord beta was not enabled because no allowed user or channel was provided.", "لم يتم تفعيل Discord التجريبي لأنك لم تضف أي مستخدم أو قناة مسموح بها.", [], "optional-capability"),
  copy("setupEditor.prompt.whatsapp.summary", "WhatsApp beta remote control needs a profile-local auth directory and allowed users.", "التحكم عن بُعد عبر WhatsApp التجريبي يحتاج مجلد مصادقة داخل الملف الشخصي ومستخدمين مسموح بهم.", [], "optional-capability"),
  copy("setupEditor.prompt.whatsapp.beta", "WhatsApp support is beta and uses experimental mode.", "دعم WhatsApp تجريبي ويستخدم الوضع التجريبي.", [], "optional-capability"),
  copy("setupEditor.prompt.whatsapp.remoteControlRisk", "WhatsApp can remotely control EstaCoda, so setup fails closed without allowed users.", "يمكن لـ WhatsApp التحكم في EstaCoda عن بُعد، لذلك يفشل الإعداد بأمان من غير مستخدمين مسموح بهم.", [], "optional-capability"),
  copy("setupEditor.prompt.whatsapp.authDir", "WhatsApp auth directory", "مجلد مصادقة WhatsApp", [], "optional-capability"),
  copy("setupEditor.prompt.whatsapp.allowedUsers", "Allowed WhatsApp phone numbers or JIDs", "أرقام WhatsApp أو JIDs المسموح بها", [], "optional-capability"),
  copy("setupEditor.prompt.whatsapp.incomplete.body", "WhatsApp beta was not enabled because no allowed user was provided.", "لم يتم تفعيل WhatsApp التجريبي لأنك لم تضف أي مستخدم مسموح به.", [], "optional-capability"),
  copy("setupEditor.prompt.voice.mode.title", "Configure voice", "اضبط الصوت", [], "optional-capability"),
  copy("setupEditor.prompt.voice.mode.body", "Choose which voice provider to configure.", "اختر مزوّد الصوت الذي تريد ضبطه.", [], "optional-capability"),
  copy("setupEditor.prompt.voice.mode.stt", "Set Speech to Text (STT) Provider", "اضبط مزوّد تحويل الكلام إلى نص (STT)", [], "optional-capability"),
  copy("setupEditor.prompt.voice.mode.stt.description", "Configure the speech-to-text provider only.", "اضبط مزوّد تحويل الكلام إلى نص فقط.", [], "optional-capability"),
  copy("setupEditor.prompt.voice.mode.tts", "Set Text to Speech (TTS) Provider", "اضبط مزوّد تحويل النص إلى كلام (TTS)", [], "optional-capability"),
  copy("setupEditor.prompt.voice.mode.tts.description", "Configure the text-to-speech provider only.", "اضبط مزوّد تحويل النص إلى كلام فقط.", [], "optional-capability"),
  copy("setupEditor.prompt.voice.summary", "Configure optional voice settings. Local STT uses managed faster-whisper by default: EstaCoda creates its Python environment at ~/.estacoda/python-env and stores model cache under ~/.estacoda/cache/huggingface. Onboarding does not ask for pythonBinary; command engines and custom Python stay outside the normal onboarding path.", "اضبط إعدادات الصوت الاختيارية. يستخدم STT المحلي faster-whisper المدار افتراضيًا: تنشئ EstaCoda بيئة Python الخاصة بها في ~/.estacoda/python-env وتخزن ذاكرة النماذج المؤقتة في ~/.estacoda/cache/huggingface. لا يطلب الإعداد pythonBinary؛ محركات الأوامر وPython المخصص خارج مسار الإعداد العادي.", [], "optional-capability"),
  copy("setupEditor.prompt.voice.ttsProvider", "TTS provider", "مزوّد TTS", [], "optional-capability"),
  copy("setupEditor.prompt.voice.ttsModel", "TTS model", "نموذج TTS", [], "optional-capability"),
  copy("setupEditor.prompt.voice.ttsApiKeyEnv", "TTS API key environment variable", "متغير بيئة مفتاح TTS API", [], "optional-capability"),
  copy("setupEditor.prompt.voice.sttProvider", "STT provider", "مزوّد STT", [], "optional-capability"),
  copy("setupEditor.prompt.voice.sttModel", "STT model", "نموذج STT", [], "optional-capability"),
  copy("setupEditor.prompt.voice.sttApiKeyEnv", "STT API key environment variable", "متغير بيئة مفتاح STT API", [], "optional-capability"),
  copy("setupEditor.prompt.vision.summary", "Configure optional image-generation settings. This does not change the primary model.", "اضبط إعدادات توليد الصور الاختيارية. هذا لا يغيّر النموذج الأساسي.", [], "optional-capability"),
  copy("setupEditor.prompt.vision.provider", "Image-generation provider", "مزوّد توليد الصور", [], "optional-capability"),
  copy("setupEditor.prompt.vision.model", "Image-generation model", "نموذج توليد الصور", [], "optional-capability"),
  copy("setupEditor.prompt.vision.apiKeyEnv", "Image-generation API key environment variable", "متغير بيئة مفتاح API لتوليد الصور", [], "optional-capability"),
  copy("setupEditor.prompt.vision.useGateway", "Use the configured image gateway setting", "استخدم إعداد image gateway المهيأ", [], "optional-capability"),
  copy("setupEditor.prompt.browser.summary", "Choose a browser backend. Setup records references only; it will not launch a browser during planning.", "اختر واجهة متصفح. يسجّل الإعداد المراجع فقط؛ ولن يشغّل متصفحًا أثناء التخطيط.", [], "optional-capability"),
  copy("setupEditor.prompt.browser.backend", "Browser backend", "واجهة المتصفح", [], "optional-capability"),
  copy("setupEditor.prompt.browser.cdpUrl", "CDP URL", "رابط CDP", [], "optional-capability"),
  copy("setupEditor.prompt.browser.launchCommand", "Browser launch command", "أمر تشغيل المتصفح", [], "optional-capability"),
  copy("setupEditor.prompt.browser.noAutoLaunch", "Setup will not launch a browser during planning.", "لن يشغّل الإعداد متصفحًا أثناء التخطيط.", [], "optional-capability"),
  copy("setupModules.provider.title", "Provider", "المزوّد", [], "provider-selection"),
  copy("setupModules.provider.review", "Provider {providerId} with model {modelId}.", "المزوّد {providerId} مع النموذج {modelId}.", ["{providerId}", "{modelId}"], "provider-selection"),
  copy("setupModules.provider.draft", "Draft provider/model update.", "مسودة تحديث المزوّد/النموذج.", [], "provider-selection"),
  copy("setupModules.credentials.title", "Credentials", "بيانات الاعتماد", [], "credential-reference"),
  copy("setupModules.credentials.review", "Credential values are not displayed. References: {envVars}.", "لا تُعرض قيم بيانات الاعتماد. المراجع: {envVars}.", ["{envVars}"], "credential-reference"),
  copy("setupModules.credentials.draft", "Draft credential reference update for {envVars}.", "مسودة تحديث مراجع بيانات الاعتماد لـ {envVars}.", ["{envVars}"], "credential-reference"),
  copy("setupModules.workspaceTrust.title", "Workspace Trust", "ثقة مساحة العمل", [], "workspace-trust"),
  copy("setupModules.workspaceTrust.review", "Workspace {workspacePath} requires explicit trust.", "مساحة العمل {workspacePath} تحتاج إلى منح ثقة صريح.", ["{workspacePath}"], "workspace-trust"),
  copy("setupModules.workspaceTrust.draft", "Draft trust grant for {workspacePath} in {trustStorePath}.", "مسودة منح الثقة لـ {workspacePath} داخل {trustStorePath}.", ["{workspacePath}", "{trustStorePath}"], "workspace-trust"),
  copy("setupModules.securityMode.title", "Security Mode", "وضع الأمان", [], "security-policy"),
  copy("setupModules.security-mode.review", "Security mode {securityMode}.", "وضع الأمان {securityMode}.", ["{securityMode}"], "security-policy"),
  copy("setupModules.security-mode.draft", "Security mode {securityMode}.", "وضع الأمان {securityMode}.", ["{securityMode}"], "security-policy"),
  copy("setupModules.workflowLearning.title", "Agent Evolution", "تطوّر الوكيل", [], "workflow-learning"),
  copy("setupModules.workflow-learning.review", "Agent Evolution {workflowMode}.", "تطوّر الوكيل {workflowMode}.", ["{workflowMode}"], "workflow-learning"),
  copy("setupModules.workflow-learning.draft", "Agent Evolution {workflowMode}.", "تطوّر الوكيل {workflowMode}.", ["{workflowMode}"], "workflow-learning"),
  copy("setupModules.telegram.title", "Telegram", "Telegram", [], "optional-capability"),
  copy("setupModules.telegram.review", "Telegram enabled with token ref {envVar} and allowed identities {identityRefs}. Remote control responds only to the allowlist.", "تم تفعيل Telegram بمرجع الرمز {envVar} والهويات المسموح بها {identityRefs}. التحكم عن بعد لا يستجيب إلا للقائمة المسموح بها.", ["{envVar}", "{identityRefs}"], "optional-capability"),
  copy("setupModules.telegram.draft", "Telegram enabled with token ref {envVar} and allowed identities {identityRefs}. Remote control responds only to the allowlist.", "تم تفعيل Telegram بمرجع الرمز {envVar} والهويات المسموح بها {identityRefs}. التحكم عن بعد لا يستجيب إلا للقائمة المسموح بها.", ["{envVar}", "{identityRefs}"], "optional-capability"),
  copy("setupModules.discord.title", "Discord beta", "Discord تجريبي", [], "optional-capability"),
  copy("setupModules.discord.review", "Discord beta enabled with token ref {envVar} and allowlist {identityRefs}. Remote control responds only to the allowlist.", "تم تفعيل Discord التجريبي بمرجع الرمز {envVar} وقائمة السماح {identityRefs}. التحكم عن بُعد لا يستجيب إلا للقائمة المسموح بها.", ["{envVar}", "{identityRefs}"], "optional-capability"),
  copy("setupModules.discord.draft", "Discord beta enabled with token ref {envVar} and allowlist {identityRefs}. Remote control responds only to the allowlist.", "تم تفعيل Discord التجريبي بمرجع الرمز {envVar} وقائمة السماح {identityRefs}. التحكم عن بُعد لا يستجيب إلا للقائمة المسموح بها.", ["{envVar}", "{identityRefs}"], "optional-capability"),
  copy("setupModules.whatsapp.title", "WhatsApp beta", "WhatsApp تجريبي", [], "optional-capability"),
  copy("setupModules.whatsapp.review", "WhatsApp beta enabled with experimental mode, auth directory {authDir}, and allowed users {allowedUsers}. Remote control responds only to the allowlist.", "تم تفعيل WhatsApp التجريبي مع الوضع التجريبي، ومجلد المصادقة {authDir}، والمستخدمين المسموح بهم {allowedUsers}. التحكم عن بُعد لا يستجيب إلا للقائمة المسموح بها.", ["{authDir}", "{allowedUsers}"], "optional-capability"),
  copy("setupModules.whatsapp.draft", "WhatsApp beta enabled with experimental mode, auth directory {authDir}, and allowed users {allowedUsers}. Remote control responds only to the allowlist.", "تم تفعيل WhatsApp التجريبي مع الوضع التجريبي، ومجلد المصادقة {authDir}، والمستخدمين المسموح بهم {allowedUsers}. التحكم عن بُعد لا يستجيب إلا للقائمة المسموح بها.", ["{authDir}", "{allowedUsers}"], "optional-capability"),
  copy("setupModules.voice.title", "Voice", "الصوت", [], "optional-capability"),
  copy("setupModules.voice.review", "Review voice provider/model without secret values. Local STT follows the managed faster-whisper path unless configured later.", "راجع مزوّد/نموذج الصوت دون قيم أسرار. يتبع STT المحلي مسار faster-whisper المدار ما لم يُضبط لاحقًا.", [], "optional-capability"),
  copy("setupModules.voice.draft", "Review voice provider/model without secret values. Local STT follows the managed faster-whisper path unless configured later.", "راجع مزوّد/نموذج الصوت دون قيم أسرار. يتبع STT المحلي مسار faster-whisper المدار ما لم يُضبط لاحقًا.", [], "optional-capability"),
  copy("setupModules.vision.title", "Vision and Image Generation", "الرؤية وتوليد الصور", [], "optional-capability"),
  copy("setupModules.vision.review", "Vision/image provider {providerId} with model {modelId}.", "مزوّد الرؤية/الصور {providerId} مع النموذج {modelId}.", ["{providerId}", "{modelId}"], "optional-capability"),
  copy("setupModules.vision.draft", "Vision/image provider {providerId} with model {modelId}.", "مزوّد الرؤية/الصور {providerId} مع النموذج {modelId}.", ["{providerId}", "{modelId}"], "optional-capability"),
  copy("setupModules.browser.title", "Browser", "المتصفح", [], "optional-capability"),
  copy("setupModules.browser.review", "Browser backend {browserBackend} is planned. It will not auto-launch during setup planning. Browser remains under control until approved.", "تم تخطيط واجهة المتصفح {browserBackend}. لن يتم تشغيلها تلقائيًا أثناء تخطيط الإعداد. يبقى المتصفح تحت السيطرة حتى تتم الموافقة.", ["{browserBackend}"], "optional-capability"),
  copy("setupModules.browser.draft", "Browser backend {browserBackend} is planned. It will not auto-launch during setup planning. Browser remains under control until approved.", "تم تخطيط واجهة المتصفح {browserBackend}. لن يتم تشغيلها تلقائيًا أثناء تخطيط الإعداد. يبقى المتصفح تحت السيطرة حتى تتم الموافقة.", ["{browserBackend}"], "optional-capability"),
  copy("setupModules.{moduleId}.blocked", "{moduleId} cannot produce normal drafts until config is repaired.", "لا يمكن لـ {moduleId} إنشاء مسودات عادية حتى يتم إصلاح الإعدادات.", ["{moduleId}"], "config-repair"),

  copy("setupReview.diagnostic", "Diagnostic item.", "عنصر تشخيص.", [], "config-repair"),
  copy("setupReview.title", "Review manifest.", "بيان المراجعة.", [], "setup-review"),
  copy("setupReview.empty", "No setup changes were drafted.", "لم تُنشأ مسودات تغييرات للإعداد.", [], "setup-review"),
  copy("setupReview.itemFallback", "Review item.", "عنصر مراجعة.", [], "setup-review"),
  copy("setupReview.bundleBlocker.summary", "Blocker: {blocker}", "مانع: {blocker}", ["{blocker}"], "config-repair"),
  copy("setupReview.bundleWarning.summary", "Warning: {warning}", "تحذير: {warning}", ["{warning}"], "config-repair"),
  copy("setupReview.sections.filesToWriteUpdate", "Configuration write.", "كتابة إعدادات.", [], "config-write"),
  copy("setupReview.sections.secretRefsToStore", "Credential write. Values are not shown.", "كتابة بيانات اعتماد. لا تُعرض القيم.", [], "credential-reference"),
  copy("setupReview.sections.workspaceTrustGrants", "Workspace trust write.", "كتابة ثقة مساحة العمل.", [], "workspace-trust"),
  copy("setupReview.sections.providerModelNetwork", "Provider, model, and network changes.", "تغييرات المزوّد والنموذج والشبكة.", [], "provider-selection"),
  copy("setupReview.sections.enabledOptionalCapabilities", "Enabled optional capabilities.", "القدرات الاختيارية المفعّلة.", [], "optional-capability"),
  copy("setupReview.sections.remoteControlSurfaces", "Remote-control surfaces and allowed identities.", "واجهات التحكم عن بعد والهويات المسموح بها.", [], "optional-capability"),
  copy("setupReview.sections.securityMode", "Security mode.", "وضع الأمان.", [], "security-policy"),
  copy("setupReview.sections.workflowLearning", "Agent Evolution mode.", "وضع تطوّر الوكيل.", [], "workflow-learning"),
  copy("setupReview.sections.verificationChecks", "Read-only verification checks.", "فحوصات تحقق للقراءة فقط.", [], "setup-verification"),
  copy("setupReview.sections.launchHandoff", "Launch handoff preference.", "تفضيل تسليم التشغيل.", [], "agent-launch"),
  copy("setupReview.sections.blockers", "Blockers that must be resolved before apply.", "موانع يجب حلّها قبل التطبيق.", [], "config-repair"),
  copy("setupReview.sections.warnings", "Warnings to review before apply.", "تحذيرات يجب مراجعتها قبل التطبيق.", [], "varies"),
  copy("setupDrafts.review", "Review setup draft.", "راجع مسودة الإعداد.", [], "varies"),
  copy("setupDrafts.providerModelRoute.summary", "Update provider/model to {providerId} / {modelId}.", "حدّث المزوّد/النموذج إلى {providerId} / {modelId}.", ["{providerId}", "{modelId}"], "provider-selection"),
  copy("setupDrafts.fallbackModelRoute.add.summary", "Add fallback model {providerId} / {modelId}.", "أضف نموذجًا احتياطيًا {providerId} / {modelId}.", ["{providerId}", "{modelId}"], "provider-selection"),
  copy("setupDrafts.fallbackModelRoute.replace.summary", "Replace fallback model {previousProviderId} / {previousModelId} with {providerId} / {modelId}.", "استبدل النموذج الاحتياطي {previousProviderId} / {previousModelId} بـ {providerId} / {modelId}.", ["{previousProviderId}", "{previousModelId}", "{providerId}", "{modelId}"], "provider-selection"),
  copy("setupDrafts.auxiliaryModelRoute.summary", "Set auxiliary {auxiliaryTask} model to {providerId} / {modelId}.", "اضبط نموذج {auxiliaryTask} المساعد إلى {providerId} / {modelId}.", ["{auxiliaryTask}", "{providerId}", "{modelId}"], "provider-selection"),
  copy("setupDrafts.credentialReference.summary", "Store credential env-var reference {envVar} only.", "احفظ مرجع متغير البيئة {envVar} فقط.", ["{envVar}"], "credential-reference"),
  copy("setupDrafts.workspaceTrust.summary", "Grant trust for {workspacePath} in {trustStorePath}.", "امنح الثقة لـ {workspacePath} داخل {trustStorePath}.", ["{workspacePath}", "{trustStorePath}"], "workspace-trust"),
  copy("setupDrafts.securityMode.summary", "Set security mode to {securityMode}.", "اضبط وضع الأمان على {securityMode}.", ["{securityMode}"], "security-policy"),
  copy("setupDrafts.workflowLearning.summary", "Set Agent Evolution to {workflowMode}.", "اضبط تطوّر الوكيل على {workflowMode}.", ["{workflowMode}"], "workflow-learning"),
  copy("setupDrafts.uiPreferences.summary", "Set interface language to {language}, interface style to {flavor}, and activity text to {activityLabels}.", "اضبط لغة الواجهة على {language}، وأسلوب الواجهة على {flavor}، ونص النشاط على {activityLabels}.", ["{language}", "{flavor}", "{activityLabels}"], "interface-preference"),
  copy("setupDrafts.optionalCapabilities.summary", "Configure optional capabilities {capabilities}.", "اضبط القدرات الاختيارية {capabilities}.", ["{capabilities}"], "optional-capability"),
  copy("setupDrafts.verification.summary", "Request read-only verification.", "اطلب تحققًا للقراءة فقط.", [], "setup-verification"),
  copy("setupDrafts.exit.summary", "Exit without applying setup changes.", "اخرج دون تطبيق تغييرات الإعداد.", [], "none"),
  copy("setupDrafts.brokenConfig.summary", "Normal editing is blocked until config is repaired.", "التحرير العادي محظور حتى يتم إصلاح الإعدادات.", [], "config-repair"),
  copy("setupDrafts.stateDirectory.summary", "Normal editing is blocked until the state directory is writable.", "التحرير العادي محظور حتى يصبح مجلد الحالة قابلًا للكتابة.", [], "config-repair"),

  copy("setupApply.review.approved", "Review approved. An apply plan can be prepared without executing it.", "تمت الموافقة على المراجعة. يمكن تجهيز خطة تطبيق دون تنفيذ.", [], "setup-review"),
  copy("setupApply.review.cancelled", "Review cancelled. No apply plan, config write, or trust grant will be created.", "أُلغيت المراجعة. لن تُنشأ خطة تطبيق أو كتابة إعدادات أو منح ثقة.", [], "none"),
  copy("setupApply.review.blocked", "Review is blocked by {blockerCount} item(s).", "المراجعة محظورة بسبب {blockerCount} عنصر/عناصر.", ["{blockerCount}"], "config-repair"),
  copy("setupApply.plan.ready", "Dry-run apply plan prepared from structured review data.", "تم تجهيز خطة تطبيق دون تنفيذ من بيانات مراجعة منظمة.", [], "config-write"),
  copy("setupApply.operations.configPatch", "Scoped config patch for {scope} in {configPath}.", "تعديل إعدادات محدود لـ {scope} داخل {configPath}.", ["{scope}", "{configPath}"], "config-write"),
  copy("setupApply.operations.credentialReference", "Credential reference operation for {envVar}.", "عملية مرجع بيانات اعتماد لـ {envVar}.", ["{envVar}"], "credential-reference"),
  copy("setupApply.operations.workspaceTrustGrant", "Explicit workspace trust grant for {workspacePath}.", "منح ثقة صريح لمساحة العمل {workspacePath}.", ["{workspacePath}"], "workspace-trust"),
  copy("setupApply.operations.verificationRequest", "Post-save verification request is read-only.", "طلب التحقق بعد الحفظ للقراءة فقط.", [], "setup-verification"),
  copy("setupApply.operations.launchHandoff", "Launch handoff requires verified readiness or explicit limited-mode acceptance.", "تسليم التشغيل يتطلب جاهزية مؤكدة أو قبولًا صريحًا للوضع المحدود.", [], "agent-launch"),
  copy("setupApply.endState.saveFailed", "Save failed: {error}. Verification or launch will not continue.", "فشل الحفظ: {error}. لن يستمر التحقق أو التشغيل.", ["{error}"], "config-write"),
  copy("setupApply.endState.verifiedReady", "Verification passed. Setup is ready.", "نجح التحقق. الإعداد جاهز.", [], "setup-verification"),
  copy("setupApply.endState.verifiedDegraded", "Verification completed with warnings. Continue only with an explicit limited-mode decision.", "اكتمل التحقق مع تحذيرات. تابع فقط بقرار صريح للوضع المحدود.", [], "setup-verification"),
  copy("setupApply.endState.verificationBlocked", "Verification blocked setup because of {blocker}. Launch will not continue.", "أوقف التحقق الإعداد بسبب: {blocker}. لن يستمر التشغيل.", ["{blocker}"], "setup-verification"),
  copy("setupApply.endState.verificationBlockedAfterPersistence", "Setup was saved, including credential persistence, but verification failed because of {blocker}. No rollback was performed.", "تم حفظ الإعداد، بما في ذلك حفظ بيانات الاعتماد، لكن فشل التحقق بسبب: {blocker}. لم يتم تنفيذ تراجع.", ["{blocker}"], "setup-verification"),
  copy("setupApply.endState.savedNotLaunched", "Setup prepared without launch handoff.", "تم تجهيز الإعداد دون تسليم للتشغيل.", [], "agent-launch"),
  copy("setupApply.endState.launched", "Launch handoff accepted.", "تم قبول تسليم التشغيل.", [], "agent-launch"),
  copy("setupApply.endState.acceptedDegraded", "Limited mode accepted for launch.", "تم قبول الوضع المحدود للتشغيل.", [], "agent-launch"),
  copy("setupApply.repairRequired", "Repair required before normal apply.", "الإصلاح مطلوب قبل التطبيق العادي.", [], "config-repair"),

  copy("setupValidation.provider.invalid", "Provider {providerId} is not available.", "المزوّد {providerId} غير متاح.", ["{providerId}"], "provider-selection"),
  copy("setupValidation.model.invalid", "Model {modelId} is not available for provider {providerId}.", "النموذج {modelId} غير متاح للمزوّد {providerId}.", ["{modelId}", "{providerId}"], "provider-selection"),
  copy("setupValidation.credential.missing", "Missing credential environment variable {envVar}.", "متغير بيئة بيانات الاعتماد {envVar} مفقود.", ["{envVar}"], "credential-reference"),
  copy("setupValidation.secret.permissionsUnsafe", "Secret store {envPath} should use mode {expectedMode}.", "يجب أن يستخدم مخزن الأسرار {envPath} الوضع {expectedMode}.", ["{envPath}", "{expectedMode}"], "credential-reference"),
  copy("setupValidation.workspace.untrusted", "Workspace {workspacePath} is not trusted.", "مساحة العمل {workspacePath} غير موثوقة.", ["{workspacePath}"], "workspace-trust"),
  copy("setupValidation.state.notWritable", "State path {statePath} is not writable.", "مسار الحالة {statePath} غير قابل للكتابة.", ["{statePath}"], "config-repair"),
  copy("setupValidation.config.broken", "Config {configPath} could not be parsed safely.", "تعذّرت قراءة ملف الإعداد {configPath} بأمان.", ["{configPath}"], "config-repair"),
  copy("setupValidation.provider.degraded", "Provider {providerId} is configured with warnings.", "المزوّد {providerId} مهيّأ مع تحذيرات.", ["{providerId}"], "provider-selection"),
  copy("setupValidation.terminal.bidiWarning", "Some Arabic terminal output may mix with technical tokens. Tokens stay isolated so lines do not become visual archaeology.", "قد يمزج بعض خرج الطرفية العربية مع رموز تقنية. ستبقى الرموز معزولة حتى لا يتحول السطر إلى تنقيب أثري.", [], "interface-preference"),
  copy("setupValidation.capability.unavailable", "Capability {capabilityId} is unavailable or incomplete.", "القدرة {capabilityId} غير متاحة أو غير مكتملة.", ["{capabilityId}"], "optional-capability"),
  copy("setupValidation.capability.skipped", "Optional capability {capabilityId} skipped. Core setup is not limited.", "تم تخطي القدرة الاختيارية {capabilityId}. الإعداد الأساسي ليس محدودًا.", ["{capabilityId}"], "optional-capability"),
  copy("setupValidation.cancel.noMutation", "Cancelled. No config, secret, trust-store, or state mutation was planned.", "تم الإلغاء. لم يتم تخطيط أي تغيير في الإعدادات أو الأسرار أو مخزن الثقة أو الحالة.", [], "none"),
  copy("setupValidation.secret.rawValueBlocked", "Raw secret values are not shown or stored in review metadata.", "لا تُعرض قيم الأسرار الخام ولا تُحفظ في بيانات المراجعة.", [], "credential-reference"),
  copy("setupValidation.remote.identityMissing", "Remote-control capability {capabilityId} requires allowed identities.", "قدرة التحكم عن بُعد {capabilityId} تتطلب هويات مسموحًا بها.", ["{capabilityId}"], "optional-capability"),
  copy("setupValidation.browser.noAutoLaunch", "Browser setup will not auto-launch {launchCommand} during planning.", "لن يشغّل إعداد المتصفح {launchCommand} تلقائيًا أثناء التخطيط.", ["{launchCommand}"], "optional-capability"),
] as const satisfies readonly SetupCopyEntry[];

export type SetupCopyKey = (typeof SETUP_COPY_ENTRIES)[number]["key"];

const COPY_BY_KEY = new Map<SetupCopyKey, SetupCopyEntry>(
  SETUP_COPY_ENTRIES.map((entry) => [entry.key, entry])
);

export function listSetupCopyEntries(): readonly SetupCopyEntry[] {
  return SETUP_COPY_ENTRIES;
}

export function getSetupCopyEntry(key: SetupCopyKey): SetupCopyEntry {
  const entry = COPY_BY_KEY.get(key);
  if (entry === undefined) {
    throw new Error(`Unknown setup copy key: ${key}`);
  }
  return entry;
}

export function hasSetupCopyKey(key: string): key is SetupCopyKey {
  return COPY_BY_KEY.has(key as SetupCopyKey);
}

export function resolveSetupCopy(
  locale: SetupCopyLocale | string,
  key: SetupCopyKey,
  options: SetupCopyResolutionOptions = {}
): string {
  const entry = getSetupCopyEntry(key);
  if (locale !== "ar") return entry.en;
  if (options.isolateArabicTechnicalTokens === false) return entry.ar;
  return isolateArabicCopy(entry.ar);
}

export function setupCopy(locale: SetupCopyLocale | string): Record<SetupCopyKey, string> {
  return Object.fromEntries(
    SETUP_COPY_ENTRIES.map((entry) => [entry.key, resolveSetupCopy(locale, entry.key)])
  ) as Record<SetupCopyKey, string>;
}

export function rawSetupCopy(locale: SetupCopyLocale, key: SetupCopyKey): string {
  const entry = getSetupCopyEntry(key);
  return locale === "ar" ? entry.ar : entry.en;
}

function copy(
  key: string,
  en: string,
  ar: string,
  placeholders: readonly string[],
  riskSurface: SetupCopyRiskSurface,
  mvp = true,
  notes?: string
): SetupCopyEntry {
  return {
    key,
    en,
    ar,
    placeholders,
    ltrPlaceholders: placeholders,
    riskSurface,
    mvp,
    ...(notes === undefined ? {} : { notes }),
  };
}

function isolateArabicCopy(value: string): string {
  let isolated = value.replace(/\{[A-Za-z][A-Za-z0-9]*\}/gu, (placeholder) => isolateLtr(placeholder));
  const tokenPattern = new RegExp(TECHNICAL_TOKENS.map(escapeRegExp).join("|"), "gu");
  return isolated.replace(tokenPattern, (token) => isolateLtr(token));
}

function escapeRegExp(value: string): string {
  return value.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
}
