import type { UiTokenContract } from "../contracts/ui-tokens.js";

export const darkTheme: UiTokenContract = {
  palette: {
    brand: "#B0B0B0",
    accent: "#B0B0B0",
    action: "#B0B0B0",
    caution: "#B0B0B0",
  },
  severity: {
    ok: "#4CAF50",
    error: "#EF5350",
    warn: "#FFA726",
    info: "#888888",
  },
  surface: {
    bg: "#1A1A1A",
    bgElevated: "#252525",
    bgInset: "#111111",
    border: "#ededed",
    borderSubtle: "#2A2A2A",
  },
  text: {
    primary: "#E8E8E8",
    secondary: "#B0B0B0",
    muted: "#707070",
    inverse: "#1A1A1A",
    agentMessage: "#E8E8E8",
  },
  interactive: {
    primary: "#5AACFF",
    primaryHover: "#7BBFFF",
    selected: "#5AACFF",
    selectedBg: "#1A3A5C",
  },
  motion: {
    waiting: { frames: ["⠋", "⠙", "⠹", "⠸", "⠼", "⠴", "⠦", "⠧", "⠇", "⠏"], cadenceMs: 85, color: "#B0B0B0" },
    thinking: { frames: ["◜", "◠", "◝", "◞", "◡", "◟"], cadenceMs: 120, color: "#B0B0B0" },
    routing: { frames: ["›", "»", "›", "·"], cadenceMs: 95, color: "#B0B0B0" },
    tool: { frames: ["◴", "◷", "◶", "◵"], cadenceMs: 90, color: "#B0B0B0" },
    worker: { frames: ["·", "∙", "•", "●", "•", "∙"], cadenceMs: 105, color: "#B0B0B0" },
    finalizing: { frames: ["◇", "◈", "◆", "◈"], cadenceMs: 120, color: "#B0B0B0" },
    background: { frames: ["⠁", "⠂", "⠄", "⡀", "⢀", "⠠", "⠐", "⠈"], cadenceMs: 160, color: "#888888" },
  },
  glyph: {
    prompt: "›",
    toolPrefix: "│",
    continuation: "…",
    bullet: "•",
    check: "✓",
    cross: "✗",
    arrow: "→",
    progress: {
      filled: "█",
      empty: "░",
      thumb: "▌",
    },
  },
  toolIcon: {
    terminal: "$",
    webSearch: "◎",
    readFile: "◰",
    writeFile: "◆",
    searchFiles: "◇",
    executeCode: "⌬",
    browserNavigate: "☞",
    delegateTask: "☷",
    mixtureOfAgents: "☵",
    memory: "☥",
    clarify: "?",
    cronjob: "◷",
    process: "⌁",
    todo: "□",
    telegram: "✉",
    media: "◉",
  },
  branding: {
    agentName: "EstaCoda",
    responseLabel: "EstaCoda",
    helpHeader: "Available Commands",
    taglinePrimary: "",
    taglineSecondary: "",
  },
  behavior: {
    allowEmoji: false,
    allowAnimation: true,
    allowAnsiColor: true,
  },
};
