import type { UiTokenContract } from "../contracts/ui-tokens.js";

export const lightTheme: UiTokenContract = {
  palette: {
    brand: "#666666",
    accent: "#666666",
    action: "#666666",
    caution: "#666666",
  },
  severity: {
    ok: "#2E7D32",
    error: "#C62828",
    warn: "#EF6C00",
    info: "#757575",
  },
  trace: {
    terminal: "#616161",
    search: "#1565C0",
    plan: "#6A1B9A",
    read: "#0277BD",
    edit: "#00796B",
    answer: "#2E7D32",
    wait: "#EF6C00",
    finish: "#2E7D32",
    failed: "#C62828",
  },
  surface: {
    bg: "#FFFFFF",
    bgElevated: "#F5F5F5",
    bgInset: "#EEEEEE",
    border: "#E0E0E0",
    borderSubtle: "#F0F0F0",
  },
  text: {
    primary: "#1A1A1A",
    secondary: "#4A4A4A",
    muted: "#8A8A8A",
    placeholder: "#6F6F6F",
    inverse: "#FFFFFF",
    agentMessage: "#1A1A1A",
  },
  interactive: {
    primary: "#0057D9",
    primaryHover: "#0047B3",
    selected: "#0057D9",
    selectedBg: "#E3F2FD",
  },
  motion: {
    waiting: { frames: ["⠋", "⠙", "⠹", "⠸", "⠼", "⠴", "⠦", "⠧", "⠇", "⠏"], cadenceMs: 85, color: "#666666" },
    thinking: { frames: ["◜", "◠", "◝", "◞", "◡", "◟"], cadenceMs: 120, color: "#666666" },
    routing: { frames: ["›", "»", "›", "·"], cadenceMs: 95, color: "#666666" },
    tool: { frames: ["◴", "◷", "◶", "◵"], cadenceMs: 90, color: "#666666" },
    worker: { frames: ["·", "∙", "•", "●", "•", "∙"], cadenceMs: 105, color: "#666666" },
    finalizing: { frames: ["◇", "◈", "◆", "◈"], cadenceMs: 120, color: "#666666" },
    background: { frames: ["⠁", "⠂", "⠄", "⡀", "⢀", "⠠", "⠐", "⠈"], cadenceMs: 160, color: "#757575" },
  },
  glyph: {
    prompt: "›",
    toolPrefix: "│",
    continuation: "…",
    bullet: "•",
    check: "✓",
    cross: "✗",
    arrow: "→",
    progress: {
      filled: "█",
      empty: "░",
      thumb: "▌",
    },
    trace: {
      event: "■",
      selected: "□",
      live: "◆",
      earlier: "‹",
    },
  },
  toolIcon: {
    terminal: "$",
    webSearch: "◎",
    readFile: "◰",
    writeFile: "◆",
    searchFiles: "◇",
    executeCode: "⌬",
    browserNavigate: "☞",
    delegateTask: "☷",
    mixtureOfAgents: "☵",
    memory: "☥",
    clarify: "?",
    cronjob: "◷",
    process: "⌁",
    todo: "□",
    telegram: "✉",
    media: "◉",
  },
  branding: {
    agentName: "EstaCoda",
    responseLabel: "EstaCoda",
    helpHeader: "Available Commands",
    taglinePrimary: "",
    taglineSecondary: "",
  },
  behavior: {
    allowEmoji: false,
    allowAnimation: true,
    allowAnsiColor: true,
  },
};
