export type RuntimeToolContext = {
  workspaceRoot: string;
  homeDir?: string;
  profileId: string;
  cronStore: import("../cron/cron-store.js").CronStore;
  trustStore: import("../security/workspace-trust-store.js").WorkspaceTrustStore;
  disableCronTools?: boolean;
  cronRuntimeControls?: {
    config: import("../config/runtime-config.js").LoadedRuntimeConfig;
    availableToolsets: () => string[];
  };
};

export type SessionToolContext = {
  workspaceRoot: string;
  profileId: string;
  sessionId: string;
  parentSessionId?: string;
  childSessionId?: string;
  currentSessionId: () => string;
  sessionRuntimeContext?: {
    currentSessionId(): string;
    rotateSession(sessionId: string): void;
  };
  homeDir?: string;
  childProcessEnv?: {
    mode: "inherit" | "isolated";
    homeDir?: string;
  };
  pythonStateRoot?: string;
  channelMediaRoot?: string;
  audioCacheRoot?: string;
  audioTempRoot?: string;
  imageCacheRoot?: string;
  browserBackend?: import("./browser.js").BrowserBackend;
  browserConfig?: Pick<import("../config/runtime-config.js").LoadedRuntimeConfig["browser"], "summarizeSnapshots" | "snapshotSummarizeThreshold">;
  mainRoute?: import("./provider.js").ResolvedModelRoute;
  visionRoute?: import("./provider.js").ResolvedAuxiliaryRoute;
  compressionRoute?: import("./provider.js").ResolvedAuxiliaryRoute;
  providerRegistry?: import("../providers/provider-registry.js").ProviderRegistry;
  providerExecutor?: import("../providers/provider-executor.js").ProviderExecutor;
  toolExecutor?: import("../tools/tool-executor.js").ToolExecutor;
  delegationManager?: import("../delegation/delegation-manager.js").DelegationManager;
  delegationConfig?: import("./delegation.js").DelegationConfig;
  trustedWorkspace?: () => Promise<boolean>;
  memoryStore?: import("../memory/memory-store.js").MemoryStore;
  memoryPersistenceService?: import("../memory/memory-persistence-service.js").MemoryPersistenceService;
  memoryPersistencePaths?: Partial<Record<import("./memory.js").MemoryFileKind, string>>;
  memoryMutationCoordinator?: import("../memory/memory-curation-coordinator.js").MemoryCurationCheckpointCoordinator;
  memoryIndexSync?: import("../memory/memory-index-sync.js").MemoryIndexWriteSync;
  memoryRetrievalService?: import("../memory/memory-retrieval-service.js").LocalMemoryRetrievalService;
  memoryInspector?: import("../memory/memory-inspector.js").MemoryInspector;
  sessionDb?: import("./session.js").SessionDB;
  trajectoryRecorder?: import("../trajectory/trajectory-recorder.js").TrajectoryRecorder;
  skillRegistry?: import("../skills/skill-registry.js").SkillRegistry;
  sessionSkillRegistry?: import("../skills/skill-registry.js").SkillRegistry;
  skillConfig?: Record<string, Record<string, unknown>>;
  processManager?: import("../process/process-manager.js").ProcessManager;
  artifactStore?: import("../artifacts/artifact-store.js").ArtifactStore;
  taskResultService?: import("../workflow/task-result-service.js").TaskResultService;
  memoryFileCompactionService?: import("../memory/memory-file-compaction-service.js").MemoryFileCompactionService;
  fileStateTracker?: import("../delegation/file-state-tracker.js").FileStateTracker;
  sessionCompressionService?: import("../prompt/session-compression-service.js").SessionCompressionService;
  sessionRecallService?: import("../session/session-recall-service.js").SessionRecallService;
  contextReferenceExpander?: import("../context/context-reference-expander.js").ContextReferenceExpander;
  projectContext?: import("./context.js").ProjectContextSnapshot;
  securityPolicy?: import("./security.js").SecurityPolicy;
  approvalController?: import("../security/workspace-approval-controller.js").WorkspaceApprovalController;
  skillLearningManager?: import("../skills/skill-learning.js").SkillLearningManager;
  memoryPromptContextBuilder?: import("../memory/memory-prompt-context-builder.js").MemoryPromptContextBuilder;
  workspaceFsAdapter?: import("../tools/workspace-tools.js").WorkspaceFsAdapter;
  webFetch?: import("../tools/web-tools.js").FetchLike;
  cdpFetch?: import("../browser/browser-backend.js").CdpFetchLike;
  cdpWebSocketFactory?: import("../browser/browser-backend.js").CdpWebSocketFactory;
  enableWebNetwork?: boolean;
  webMaxContentChars?: number;
  webConfig?: Pick<import("../config/runtime-config.js").LoadedRuntimeConfig["web"], "backend" | "searchBackend" | "extractBackend" | "crawlBackend" | "brave">;
  securityConfig?: Pick<import("../config/runtime-config.js").LoadedRuntimeConfig["security"], "allowPrivateUrls" | "websiteBlocklist">;
  voiceFetch?: import("../tools/voice-tools.js").VoiceFetchLike;
  localWhisper?: import("../tools/stt-local-whisper.js").FasterWhisperWorker;
  tts?: import("../config/runtime-config.js").LoadedRuntimeConfig["tts"];
  stt?: import("../config/runtime-config.js").LoadedRuntimeConfig["stt"];
  imageGen?: import("../config/runtime-config.js").LoadedRuntimeConfig["imageGen"];
  imageGenerationFetch?: import("../tools/image-generation-tools.js").ImageGenerationFetchLike;
  localSkillsRoot?: string;
  bundledSkillsRoot?: string;
  skillEvolutionStore?: import("../skills/skill-evolution.js").SkillEvolutionStore;
  changeManifestStore?: import("../skills/change-manifest-store.js").ChangeManifestStore;
  memoryPromotionStore?: import("../memory/memory-promotion-store.js").MemoryPromotionStore;
  externalMemory?: import("../memory/external-memory-provider.js").ExternalMemoryRuntimeConfig;
  externalMemoryConfig?: import("../memory/external-memory-provider.js").ExternalMemoryRuntimeConfig;
  externalMemoryProviders?: import("../contracts/memory.js").ExternalMemoryProvider[];
};
