#!/usr/bin/env bash
set -euo pipefail

INSTALLER_VERSION="v0.1.0-prerelease"
SKIP_INIT=0

usage() {
  cat <<'USAGE'
EstaCoda manual source setup

Usage:
  git clone https://github.com/sifr01-labs/EstaCoda.git
  cd EstaCoda
  ./scripts/setup-estacoda.sh [--skip-init]

Options:
  --skip-init  Do not run `estacoda init` after building
  -h, --help   Show this help without changing files
USAGE
}

die() {
  echo "Error: $*" >&2
  exit 1
}

command_exists() {
  command -v "$1" >/dev/null 2>&1
}

while [ "$#" -gt 0 ]; do
  case "$1" in
    --skip-init)
      SKIP_INIT=1
      shift
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    *)
      die "Unknown option: $1"
      ;;
  esac
done

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd -P)"

shell_quote() {
  printf "'%s'" "$(printf '%s' "$1" | sed "s/'/'\\\\''/g")"
}

is_termux() {
  [ -n "${TERMUX_VERSION:-}" ] || [[ "${PREFIX:-}" == *"/com.termux/"* ]]
}

detect_platform() {
  local os arch
  os="$(uname -s)"
  arch="$(uname -m)"

  case "$arch" in
    x86_64|amd64|arm64|aarch64) ;;
    *) die "Unsupported CPU architecture: $arch" ;;
  esac

  case "$os" in
    Darwin)
      if command_exists sw_vers; then
        local mac_version mac_major
        mac_version="$(sw_vers -productVersion)"
        mac_major="${mac_version%%.*}"
        if [ "${mac_major:-0}" -lt 11 ]; then
          die "macOS 11 Big Sur or newer is required. Found: $mac_version"
        fi
      fi
      ;;
    Linux)
      if is_termux; then
        return 0
      fi
      if command_exists getconf && getconf GNU_LIBC_VERSION >/dev/null 2>&1; then
        return 0
      fi
      if command_exists ldd && ldd --version 2>&1 | head -n 1 | grep -Eiq 'glibc|gnu libc'; then
        return 0
      fi
      die "A modern Linux distribution with glibc is required for manual source setup."
      ;;
    *)
      die "Unsupported operating system: $os"
      ;;
  esac
}

validate_node() {
  if ! command_exists node; then
    die "Node.js >= 22.18.0 is required but was not found on PATH."
  fi
  local node_version
  node_version="$(node --version 2>/dev/null || true)"
  if ! node -e 'const [major, minor, patch] = process.versions.node.split(".").map(Number); process.exit(major > 22 || (major === 22 && (minor > 18 || (minor === 18 && patch >= 0))) ? 0 : 1);' >/dev/null 2>&1; then
    die "Node.js >= 22.18.0 is required. Found: ${node_version:-unknown}"
  fi
  echo "Node: $node_version"
}

ensure_pnpm() {
  if command_exists corepack; then
    if ! corepack enable >/dev/null 2>&1; then
      echo "Warning: corepack enable failed; checking for pnpm on PATH." >&2
    fi
  else
    echo "Warning: Corepack was not found; checking for pnpm on PATH." >&2
  fi

  if ! command_exists pnpm; then
    die "pnpm is required. Install a Node.js distribution with Corepack or install pnpm manually."
  fi
  local pnpm_version
  if ! pnpm_version="$(pnpm --version 2>/dev/null)"; then
    die "pnpm is present but could not run. Check Corepack/pnpm installation and network access for package-manager activation."
  fi
  echo "pnpm: $pnpm_version"
}

detect_git_metadata() {
  SOURCE_URL="unknown"
  BRANCH="unknown"
  if command_exists git && git -C "$REPO_ROOT" rev-parse --is-inside-work-tree >/dev/null 2>&1; then
    SOURCE_URL="$(git -C "$REPO_ROOT" remote get-url origin 2>/dev/null || printf 'unknown')"
    BRANCH="$(git -C "$REPO_ROOT" branch --show-current 2>/dev/null || printf 'unknown')"
    if [ -z "$BRANCH" ]; then
      BRANCH="unknown"
    fi
  fi
}

choose_bin_dir() {
  if is_termux; then
    [ -n "${PREFIX:-}" ] || die "PREFIX is required for Termux setup."
    BIN_DIR="$PREFIX/bin"
  else
    [ -n "${HOME:-}" ] || die "HOME is not set."
    BIN_DIR="$HOME/.local/bin"
  fi
}

build_source() {
  echo "Installing dependencies and building dist/"
  (
    cd "$REPO_ROOT"
    CI=true pnpm install --frozen-lockfile
    pnpm run build
  )
}

write_wrapper() {
  local wrapper="$BIN_DIR/estacoda"
  local quoted_root
  quoted_root="$(shell_quote "$REPO_ROOT")"
  mkdir -p "$BIN_DIR"

  if [ -e "$wrapper" ] || [ -L "$wrapper" ]; then
    if ! grep -Eq "Generated by scripts/(install|setup-estacoda)\\.sh|EstaCoda Node/dist wrapper|EstaCoda dist entrypoint" "$wrapper" 2>/dev/null; then
      die "Refusing to overwrite existing non-EstaCoda command: $wrapper"
    fi
  fi

  if [ -d "$wrapper" ]; then
    die "Refusing to overwrite existing non-EstaCoda command: $wrapper"
  fi

  cat > "$wrapper" <<WRAPPER
#!/usr/bin/env bash
set -euo pipefail
# EstaCoda source wrapper. Generated by scripts/setup-estacoda.sh.
REPO_ROOT=$quoted_root
ENTRYPOINT="\$REPO_ROOT/dist/index.js"
if [ ! -f "\$ENTRYPOINT" ]; then
  echo "EstaCoda dist entrypoint not found: \$ENTRYPOINT" >&2
  echo "Run: cd \"\$REPO_ROOT\" && corepack enable && pnpm install --frozen-lockfile && pnpm run build" >&2
  exit 1
fi
exec node "\$ENTRYPOINT" "\$@"
WRAPPER
  chmod +x "$wrapper"
}

write_stamp() {
  local stamp_path="$REPO_ROOT/.install-method.json"
  node --input-type=module - "$stamp_path" "manual-source" "$SOURCE_URL" "$BRANCH" "$REPO_ROOT" "$INSTALLER_VERSION" <<'NODE'
import { writeFileSync } from "node:fs";

const [stampPath, method, sourceUrl, branch, installDir, installerVersion] = process.argv.slice(2);
const stamp = {
  method,
  sourceUrl,
  branch,
  installDir,
  installedAt: new Date().toISOString(),
  installerVersion
};
writeFileSync(stampPath, `${JSON.stringify(stamp, null, 2)}\n`);
NODE
}

run_init() {
  if [ "$SKIP_INIT" -eq 1 ]; then
    echo "Skipping estacoda init because --skip-init was provided."
    return 0
  fi
  echo "Initializing EstaCoda state"
  HOME="${HOME:-}" "$BIN_DIR/estacoda" init
}

echo "EstaCoda manual source setup"
detect_platform
validate_node
ensure_pnpm
detect_git_metadata
choose_bin_dir

echo "Repo root: $REPO_ROOT"
echo "Source: $SOURCE_URL"
echo "Branch: $BRANCH"
echo "Bin dir: $BIN_DIR"

build_source
write_stamp
write_wrapper
run_init

echo ""
echo "EstaCoda source checkout is set up."
echo "Command: $BIN_DIR/estacoda"
echo ""
echo "Next steps:"
if [[ ":$PATH:" != *":$BIN_DIR:"* ]]; then
  echo "  1. Add to PATH: export PATH=\"$BIN_DIR:\$PATH\""
  echo "  2. Run: estacoda setup"
  echo "  3. Run: estacoda"
else
  echo "  1. Run: estacoda setup"
  echo "  2. Run: estacoda"
fi
