import { constants } from "node:fs";
import { access, lstat, readFile, readlink, readdir, rm, writeFile } from "node:fs/promises";
import { dirname, join, parse, resolve, sep } from "node:path";
import { defaultProfileId, readActiveProfile, resolveGlobalStateHome, resolveProfileStateHome } from "../config/profile-home.js";
import { resolveOsHomeDir } from "../config/home-dir.js";
import { detectInstallMethod, type InstallMethodInfo } from "./install-method.js";
import { uninstallService } from "../gateway/service-manager.js";

export type UninstallMode = "keep-data" | "purge";

export type UninstallOptions = {
  mode?: UninstallMode;
  yes?: boolean;
  homeDir?: string;
  profileId?: string;
  env?: NodeJS.ProcessEnv;
  installMethodInfo?: InstallMethodInfo;
  detectInstallMethod?: () => Promise<InstallMethodInfo>;
  wrapperPaths?: readonly string[];
  teardownGateway?: (options: { homeDir: string; serviceUserHomeDir: string; profileId: string; termux: boolean }) => Promise<TeardownResult>;
};

export type TeardownResult = {
  ok: boolean;
  message: string;
};

export type UninstallResult = {
  exitCode: number;
  output: string;
};

type TrustedManagedSource = {
  trusted: true;
  installDir: string;
  sourceUrl: string;
  branch: string;
};

type UntrustedManagedSource = {
  trusted: false;
  reason: string;
};

const WRAPPER_MARKERS = [
  "Generated by scripts/install.sh",
  "Generated by scripts/setup-estacoda.sh",
  "EstaCoda Node/dist wrapper",
  "EstaCoda dist entrypoint",
  "EstaCoda source wrapper"
] as const;

export async function runUninstall(options: UninstallOptions = {}): Promise<UninstallResult> {
  const env = options.env ?? process.env;
  const homeDir = options.homeDir ?? env.HOME ?? "";
  if (homeDir.trim().length === 0) {
    return { exitCode: 1, output: "Error: HOME is not set. Set HOME before uninstalling EstaCoda." };
  }

  const mode = options.mode ?? "keep-data";
  if (mode === "purge" && options.yes !== true) {
    return {
      exitCode: 1,
      output: [
        "Full purge removes EstaCoda user data under ~/.estacoda.",
        "Re-run with --purge --yes to confirm.",
        "--yes without --purge keeps user data."
      ].join("\n")
    };
  }

  const profileId = options.profileId ?? safeReadActiveProfile(homeDir);
  const state = resolveGlobalStateHome({ homeDir });
  const installMethod = options.installMethodInfo ?? await (options.detectInstallMethod ?? (() => detectInstallMethod({
    includeCwd: false,
    entrypointPath: process.argv[1],
    moduleUrl: import.meta.url
  })))();
  const termux = isTermux(env);
  const lines: string[] = [
    "EstaCoda uninstall",
    `Mode: ${mode === "purge" ? "purge" : "keep data"}`,
    `Detected install method: ${installMethod.method}`
  ];

  if (termux) {
    lines.push("Termux detected: system service teardown is skipped; known Termux wrapper paths are cleaned best-effort.");
  }

  const teardown = await (options.teardownGateway ?? teardownGatewayService)({
    homeDir,
    serviceUserHomeDir: resolveOsHomeDir(env),
    profileId,
    termux
  });
  lines.push(`Gateway teardown: ${teardown.message}`);

  const effectiveMethod = effectiveUninstallMethod(installMethod, homeDir);
  if (installMethod.method === "managed-source" && effectiveMethod.method === "manual-source") {
    lines.push(`Managed-source stamp was not trusted: ${effectiveMethod.reason}`);
    lines.push("Treating this checkout as manual-source; no repo directory will be removed.");
  }

  if (effectiveMethod.method === "managed-source") {
    const wrapperReport = await removeSourceWrappers(wrapperPaths(homeDir, env, options.wrapperPaths));
    lines.push(...wrapperReport);
    lines.push(...await cleanupPathEntries(homeDir));
    await rm(effectiveMethod.installDir, { recursive: true, force: true });
    lines.push(`Removed managed install directory: ${effectiveMethod.installDir}`);
  } else if (effectiveMethod.method === "manual-source" || effectiveMethod.method === "unknown") {
    const wrapperReport = await removeSourceWrappers(wrapperPaths(homeDir, env, options.wrapperPaths));
    lines.push(...wrapperReport);
    lines.push(...await cleanupPathEntries(homeDir));
    if (effectiveMethod.method === "manual-source" && installMethod.installDir !== undefined) {
      lines.push(`Manual source checkout preserved: ${installMethod.installDir}`);
    }
  } else {
    lines.push(...packageManagerGuidance(effectiveMethod.method));
  }

  if (mode === "purge") {
    lines.push(...await purgeUserState({ homeDir, profileId, stateRoot: state.stateRoot }));
  } else {
    lines.push("User data preserved: ~/.estacoda");
  }

  lines.push("Native Windows uninstall is not supported in v0.1.0. WSL2 remains best-effort.");
  return { exitCode: 0, output: lines.join("\n") };
}

function safeReadActiveProfile(homeDir: string): string {
  try {
    return readActiveProfile({ homeDir }).profileId;
  } catch {
    return defaultProfileId();
  }
}

function effectiveUninstallMethod(info: InstallMethodInfo, homeDir: string):
  | ({ method: "managed-source" } & TrustedManagedSource)
  | { method: Exclude<InstallMethodInfo["method"], "managed-source"> | "manual-source"; reason?: string } {
  if (info.method !== "managed-source") {
    return { method: info.method };
  }

  const trust = trustManagedSource(info, homeDir);
  if (!trust.trusted) {
    return { method: "manual-source", reason: trust.reason };
  }

  return { method: "managed-source", ...trust };
}

function trustManagedSource(info: InstallMethodInfo, homeDir: string): TrustedManagedSource | UntrustedManagedSource {
  const installDir = info.installDir?.trim();
  const sourceUrl = info.sourceUrl?.trim();
  const branch = (info.expectedBranch ?? info.branch)?.trim();
  const stampPath = info.stampPath?.trim();

  if (info.source !== "stamp") {
    return { trusted: false, reason: "install method did not come from an explicit stamp" };
  }
  if (installDir === undefined || installDir.length === 0) {
    return { trusted: false, reason: "managed-source stamp is missing installDir" };
  }
  if (sourceUrl === undefined || sourceUrl.length === 0) {
    return { trusted: false, reason: "managed-source stamp is missing sourceUrl" };
  }
  if (branch === undefined || branch.length === 0) {
    return { trusted: false, reason: "managed-source stamp is missing branch metadata" };
  }
  if (stampPath === undefined || stampPath.length === 0) {
    return { trusted: false, reason: "managed-source stamp path is missing" };
  }

  const resolvedInstallDir = resolve(installDir);
  if (dirname(resolve(stampPath)) !== resolvedInstallDir) {
    return { trusted: false, reason: "managed-source installDir does not match the stamp root" };
  }
  if (!isSafeManagedInstallDir(resolvedInstallDir, homeDir)) {
    return { trusted: false, reason: "managed-source installDir is not safe to remove automatically" };
  }

  return {
    trusted: true,
    installDir: resolvedInstallDir,
    sourceUrl,
    branch
  };
}

function isSafeManagedInstallDir(installDir: string, homeDir: string): boolean {
  const root = parse(installDir).root;
  const home = resolve(homeDir);
  const stateRoot = resolveGlobalStateHome({ homeDir }).stateRoot;
  if (installDir === root || installDir === home || installDir === stateRoot) {
    return false;
  }

  const basename = installDir.split(sep).filter(Boolean).at(-1)?.toLowerCase();
  return basename === "estacoda" || basename === "estacoda.git" || basename === "estacoda-source";
}

async function teardownGatewayService(options: { homeDir: string; serviceUserHomeDir: string; profileId: string; termux: boolean }): Promise<TeardownResult> {
  if (options.termux) {
    return { ok: true, message: "skipped service-manager teardown on Termux" };
  }

  const result = await uninstallService({
    serviceUserHomeDir: options.serviceUserHomeDir,
    profileId: options.profileId
  });

  if (result.ok) {
    return { ok: true, message: "managed service uninstall attempted successfully" };
  }

  return {
    ok: false,
    message: `no managed service was removed (${result.error}). If a gateway is running, stop it with: estacoda gateway stop`
  };
}

function wrapperPaths(homeDir: string, env: NodeJS.ProcessEnv, override?: readonly string[]): string[] {
  if (override !== undefined) {
    return [...override];
  }

  const paths = [
    join(homeDir, ".local", "bin", "estacoda"),
    join(homeDir, ".estacoda", "bin", "estacoda"),
    "/usr/local/bin/estacoda"
  ];

  if (env.PREFIX !== undefined && env.PREFIX.trim().length > 0) {
    paths.push(join(env.PREFIX, "bin", "estacoda"));
  }

  return [...new Set(paths.map((path) => resolve(path)))];
}

async function removeSourceWrappers(paths: readonly string[]): Promise<string[]> {
  const lines: string[] = [];

  for (const path of paths) {
    const removal = await removeKnownWrapper(path);
    if (removal !== undefined) {
      lines.push(removal);
    }
  }

  if (lines.length === 0) {
    lines.push("Wrapper cleanup: no known EstaCoda source wrappers found.");
  }

  return lines;
}

async function removeKnownWrapper(path: string): Promise<string | undefined> {
  let stats;
  try {
    stats = await lstat(path);
  } catch (error) {
    return isMissing(error) ? undefined : `Wrapper cleanup skipped ${path}: ${messageFor(error)}`;
  }

  if (stats.isSymbolicLink()) {
    const target = await readSymlinkSafe(path);
    if (target !== undefined && isKnownWrapperTarget(target)) {
      await rm(path, { force: true });
      return `Removed wrapper: ${path}`;
    }
    return `Wrapper left in place (not an EstaCoda source wrapper): ${path}`;
  }

  if (!stats.isFile()) {
    return `Wrapper left in place (not a file/symlink): ${path}`;
  }

  let content: string;
  try {
    content = await readFile(path, "utf8");
  } catch (error) {
    return `Wrapper left in place (could not inspect): ${path} (${messageFor(error)})`;
  }

  if (!WRAPPER_MARKERS.some((marker) => content.includes(marker))) {
    return `Wrapper left in place (not an EstaCoda source wrapper): ${path}`;
  }

  await rm(path, { force: true });
  return `Removed wrapper: ${path}`;
}

async function readSymlinkSafe(path: string): Promise<string | undefined> {
  try {
    return await readlink(path);
  } catch {
    return undefined;
  }
}

function isKnownWrapperTarget(target: string): boolean {
  const normalized = target.replace(/\\/gu, "/").toLowerCase();
  return normalized.includes("estacoda-wrapper.sh") ||
    normalized.includes("dist/index.js") ||
    normalized.includes("/estacoda/");
}

async function cleanupPathEntries(homeDir: string): Promise<string[]> {
  const files = [".bashrc", ".zshrc", ".profile", ".bash_profile"].map((file) => join(homeDir, file));
  const lines: string[] = [];

  for (const file of files) {
    const result = await cleanupPathFile(file);
    if (result !== undefined) {
      lines.push(result);
    }
  }

  if (lines.length === 0) {
    lines.push("PATH cleanup: no EstaCoda-owned shell config entries found.");
  }

  return lines;
}

async function cleanupPathFile(path: string): Promise<string | undefined> {
  let content: string;
  try {
    content = await readFile(path, "utf8");
  } catch (error) {
    return isMissing(error) ? undefined : `PATH cleanup skipped ${path}: ${messageFor(error)}`;
  }

  const sourceLines = content.split(/\r?\n/u);
  const kept = sourceLines.filter((line) => !isInstallerPathLine(line));
  if (kept.length === sourceLines.length) {
    return undefined;
  }

  const next = kept.join("\n");
  await writeFile(path, next.endsWith("\n") ? next : `${next}\n`, "utf8");
  return `Removed EstaCoda PATH entries from: ${path}`;
}

function isInstallerPathLine(line: string): boolean {
  const trimmed = line.trim();
  if (trimmed.length === 0 || !trimmed.includes("PATH=")) {
    return false;
  }

  return /estacoda/i.test(trimmed) && (
    /EstaCoda installer|estacoda installer|\.estacoda\/bin|\.local\/bin|\/usr\/local\/bin/u.test(trimmed)
  );
}

function packageManagerGuidance(method: Exclude<InstallMethodInfo["method"], "managed-source" | "manual-source" | "unknown">): string[] {
  switch (method) {
    case "npm-global":
      return [
        "npm global install detected. Let npm remove package-owned bin stubs.",
        "Run: npm uninstall -g estacoda",
        "User data preserved by default: ~/.estacoda"
      ];
    case "pnpm-global":
      return [
        "pnpm global install detected. Let pnpm remove package-owned bin stubs.",
        "Run: pnpm remove -g estacoda",
        "User data preserved by default: ~/.estacoda"
      ];
    case "homebrew":
      return [
        "Homebrew install detected. Let Homebrew remove package-owned files.",
        "Run: brew uninstall estacoda",
        "Tap removal is not automatic. Use brew untap kemetresearch/tap only if you explicitly want that."
      ];
    case "docker":
      return [
        "Docker/container install detected. EstaCoda will not mutate containers, images, or volumes automatically.",
        "Run: docker pull ghcr.io/sifr01-labs/estacoda:latest for updates, or remove containers/images manually when safe.",
        "Named or bind-mounted state volumes are preserved by default."
      ];
  }
}

async function purgeUserState(options: { homeDir: string; profileId: string; stateRoot: string }): Promise<string[]> {
  if (!await exists(options.stateRoot)) {
    return ["User data purge: ~/.estacoda was already absent."];
  }

  const otherProfiles = await listOtherProfiles(options.homeDir, options.profileId);
  if (otherProfiles.length > 0) {
    const profileRoot = resolveProfileStateHome({ homeDir: options.homeDir, profileId: options.profileId }).profileRoot;
    await rm(profileRoot, { recursive: true, force: true });
    return [
      `Removed active profile state: ${profileRoot}`,
      `Preserved ${otherProfiles.length} other named profile(s): ${otherProfiles.join(", ")}`,
      "Full multi-profile purge requires an explicit future flag; --yes keeps the safe default for other profiles."
    ];
  }

  await rm(options.stateRoot, { recursive: true, force: true });
  return ["Removed user data: ~/.estacoda"];
}

async function listOtherProfiles(homeDir: string, profileId: string): Promise<string[]> {
  const profilesRoot = resolveGlobalStateHome({ homeDir }).profilesRoot;
  try {
    const entries = await readdir(profilesRoot, { withFileTypes: true });
    return entries
      .filter((entry) => entry.isDirectory())
      .map((entry) => entry.name)
      .filter((name) => name !== profileId)
      .sort();
  } catch (error) {
    return isMissing(error) ? [] : [];
  }
}

function isTermux(env: NodeJS.ProcessEnv): boolean {
  return env.PREFIX?.includes("com.termux") === true || env.TERMUX_VERSION !== undefined;
}

async function exists(path: string): Promise<boolean> {
  try {
    await access(path, constants.F_OK);
    return true;
  } catch {
    return false;
  }
}

function isMissing(error: unknown): boolean {
  return error instanceof Error && "code" in error && (error.code === "ENOENT" || error.code === "ENOTDIR");
}

function messageFor(error: unknown): string {
  return error instanceof Error ? error.message : String(error);
}
