import { existsSync, mkdtempSync, readFileSync, writeFileSync } from "node:fs";
import { mkdir, symlink, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { describe, expect, it } from "vitest";
import { runUninstall, type TeardownResult } from "./uninstall.js";
import type { InstallMethodInfo } from "./install-method.js";

describe("runUninstall", () => {
  it("removes managed-source install dir and known wrapper while preserving user data by default", async () => {
    const temp = mkdtempSync(join(tmpdir(), "estacoda-uninstall-managed-"));
    const homeDir = join(temp, "home");
    const installDir = join(temp, "estacoda");
    const wrapper = join(temp, "bin", "estacoda");
    await mkdir(join(homeDir, ".estacoda", "profiles", "default"), { recursive: true });
    await mkdir(installDir, { recursive: true });
    await mkdir(join(temp, "bin"), { recursive: true });
    await writeFile(wrapper, "#!/usr/bin/env bash\n# EstaCoda source wrapper. Generated by scripts/install.sh.\n", "utf8");

    const result = await runUninstall({
      homeDir,
      installMethodInfo: managedSource(installDir),
      wrapperPaths: [wrapper],
      teardownGateway: async () => {
        expect(existsSync(installDir)).toBe(true);
        return okTeardown();
      }
    });

    expect(result.exitCode).toBe(0);
    expect(existsSync(installDir)).toBe(false);
    expect(existsSync(wrapper)).toBe(false);
    expect(existsSync(join(homeDir, ".estacoda"))).toBe(true);
    expect(result.output).toContain("Gateway teardown:");
    expect(result.output).toContain("User data preserved");
  });

  it("purges user data only when --purge is confirmed with yes", async () => {
    const temp = mkdtempSync(join(tmpdir(), "estacoda-uninstall-purge-"));
    const homeDir = join(temp, "home");
    const installDir = join(temp, "estacoda");
    await mkdir(join(homeDir, ".estacoda", "profiles", "default"), { recursive: true });
    await mkdir(installDir, { recursive: true });

    const unconfirmed = await runUninstall({
      mode: "purge",
      yes: false,
      homeDir,
      installMethodInfo: managedSource(installDir),
      teardownGateway: async () => okTeardown()
    });
    expect(unconfirmed.exitCode).toBe(1);
    expect(existsSync(join(homeDir, ".estacoda"))).toBe(true);
    expect(existsSync(installDir)).toBe(true);

    const confirmed = await runUninstall({
      mode: "purge",
      yes: true,
      homeDir,
      installMethodInfo: managedSource(installDir),
      wrapperPaths: [],
      teardownGateway: async () => okTeardown()
    });
    expect(confirmed.exitCode).toBe(0);
    expect(existsSync(join(homeDir, ".estacoda"))).toBe(false);
    expect(existsSync(installDir)).toBe(false);
  });

  it("does not delete user data when --yes is used without --purge", async () => {
    const temp = mkdtempSync(join(tmpdir(), "estacoda-uninstall-yes-"));
    const homeDir = join(temp, "home");
    const installDir = join(temp, "estacoda");
    await mkdir(join(homeDir, ".estacoda"), { recursive: true });
    await mkdir(installDir, { recursive: true });

    const result = await runUninstall({
      yes: true,
      homeDir,
      installMethodInfo: managedSource(installDir),
      wrapperPaths: [],
      teardownGateway: async () => okTeardown()
    });

    expect(result.exitCode).toBe(0);
    expect(existsSync(join(homeDir, ".estacoda"))).toBe(true);
  });

  it("treats untrusted managed-source stamps as manual-source and preserves the repo", async () => {
    const temp = mkdtempSync(join(tmpdir(), "estacoda-uninstall-untrusted-"));
    const homeDir = join(temp, "home");
    const installDir = join(temp, "custom-checkout");
    await mkdir(installDir, { recursive: true });

    const result = await runUninstall({
      homeDir,
      installMethodInfo: {
        ...managedSource(installDir),
        sourceUrl: undefined
      },
      wrapperPaths: [],
      teardownGateway: async () => okTeardown()
    });

    expect(result.exitCode).toBe(0);
    expect(existsSync(installDir)).toBe(true);
    expect(result.output).toContain("Treating this checkout as manual-source");
  });

  it("refuses managed-source deletion when installDir does not match the stamp root", async () => {
    const temp = mkdtempSync(join(tmpdir(), "estacoda-uninstall-stamp-root-"));
    const homeDir = join(temp, "home");
    const installDir = join(temp, "estacoda");
    await mkdir(installDir, { recursive: true });

    const result = await runUninstall({
      homeDir,
      installMethodInfo: {
        ...managedSource(installDir),
        stampPath: join(temp, "other-estacoda", ".install-method.json")
      },
      wrapperPaths: [],
      teardownGateway: async () => okTeardown()
    });

    expect(result.exitCode).toBe(0);
    expect(existsSync(installDir)).toBe(true);
    expect(result.output).toContain("installDir does not match the stamp root");
  });

  it("refuses managed-source deletion for broad home or state-root paths", async () => {
    const temp = mkdtempSync(join(tmpdir(), "estacoda-uninstall-broad-"));
    const homeDir = join(temp, "home");
    await mkdir(join(homeDir, ".estacoda"), { recursive: true });

    for (const installDir of [homeDir, join(homeDir, ".estacoda")]) {
      const result = await runUninstall({
        homeDir,
        installMethodInfo: managedSource(installDir),
        wrapperPaths: [],
        teardownGateway: async () => okTeardown()
      });

      expect(result.exitCode).toBe(0);
      expect(existsSync(installDir)).toBe(true);
      expect(result.output).toContain("not safe to remove automatically");
    }
  });

  it("preserves manual-source clones while removing known wrappers and owned PATH lines", async () => {
    const temp = mkdtempSync(join(tmpdir(), "estacoda-uninstall-manual-"));
    const homeDir = join(temp, "home");
    const cloneDir = join(temp, "manual-clone");
    const wrapper = join(temp, "bin", "estacoda");
    await mkdir(cloneDir, { recursive: true });
    await mkdir(join(temp, "bin"), { recursive: true });
    await mkdir(homeDir, { recursive: true });
    await writeFile(wrapper, "#!/usr/bin/env bash\n# EstaCoda source wrapper. Generated by scripts/setup-estacoda.sh.\n", "utf8");
    writeFileSync(join(homeDir, ".zshrc"), [
      "export PATH=\"$HOME/.estacoda/bin:$PATH\" # EstaCoda installer",
      "export PATH=\"$HOME/.cargo/bin:$PATH\""
    ].join("\n"));

    const result = await runUninstall({
      homeDir,
      installMethodInfo: manualSource(cloneDir),
      wrapperPaths: [wrapper],
      teardownGateway: async () => okTeardown()
    });

    expect(result.exitCode).toBe(0);
    expect(existsSync(cloneDir)).toBe(true);
    expect(existsSync(wrapper)).toBe(false);
    expect(readFileSync(join(homeDir, ".zshrc"), "utf8")).toContain(".cargo/bin");
    expect(readFileSync(join(homeDir, ".zshrc"), "utf8")).not.toContain(".estacoda/bin");
  });

  it("refuses to remove unknown wrapper files", async () => {
    const temp = mkdtempSync(join(tmpdir(), "estacoda-uninstall-wrapper-"));
    const homeDir = join(temp, "home");
    const wrapper = join(temp, "bin", "estacoda");
    await mkdir(join(temp, "bin"), { recursive: true });
    await writeFile(wrapper, "#!/usr/bin/env bash\necho not-estacoda\n", "utf8");

    const result = await runUninstall({
      homeDir,
      installMethodInfo: manualSource(join(temp, "manual")),
      wrapperPaths: [wrapper],
      teardownGateway: async () => okTeardown()
    });

    expect(result.exitCode).toBe(0);
    expect(existsSync(wrapper)).toBe(true);
    expect(result.output).toContain("Wrapper left in place");
  });

  it("removes symlink wrappers only when the target is a known EstaCoda target", async () => {
    const temp = mkdtempSync(join(tmpdir(), "estacoda-uninstall-symlink-"));
    const homeDir = join(temp, "home");
    const binDir = join(temp, "bin");
    const known = join(binDir, "estacoda");
    const unknown = join(binDir, "other-estacoda");
    await mkdir(join(temp, "source", "dist"), { recursive: true });
    await mkdir(binDir, { recursive: true });
    await writeFile(join(temp, "source", "dist", "index.js"), "", "utf8");
    await symlink(join(temp, "source", "dist", "index.js"), known);
    await symlink("/usr/bin/env", unknown);

    const result = await runUninstall({
      homeDir,
      installMethodInfo: manualSource(join(temp, "manual")),
      wrapperPaths: [known, unknown],
      teardownGateway: async () => okTeardown()
    });

    expect(result.exitCode).toBe(0);
    expect(existsSync(known)).toBe(false);
    expect(existsSync(unknown)).toBe(true);
  });

  it("delegates npm, pnpm, Homebrew, and Docker uninstall without removing package-owned wrappers", async () => {
    const temp = mkdtempSync(join(tmpdir(), "estacoda-uninstall-package-"));
    const homeDir = join(temp, "home");
    const wrapper = join(temp, "bin", "estacoda");
    await mkdir(join(temp, "bin"), { recursive: true });
    await writeFile(wrapper, "#!/usr/bin/env node\n", "utf8");

    for (const method of ["npm-global", "pnpm-global", "homebrew", "docker"] as const) {
      const result = await runUninstall({
        homeDir,
        installMethodInfo: packageMethod(method),
        wrapperPaths: [wrapper],
        teardownGateway: async () => okTeardown()
      });

      expect(result.exitCode).toBe(0);
      expect(existsSync(wrapper)).toBe(true);
      expect(result.output).toMatch(/npm uninstall -g estacoda|pnpm remove -g estacoda|brew uninstall estacoda|Docker\/container install detected/u);
    }
  });

  it("keeps other named profiles under --purge --yes", async () => {
    const temp = mkdtempSync(join(tmpdir(), "estacoda-uninstall-profiles-"));
    const homeDir = join(temp, "home");
    const installDir = join(temp, "estacoda");
    await mkdir(join(homeDir, ".estacoda", "profiles", "default"), { recursive: true });
    await mkdir(join(homeDir, ".estacoda", "profiles", "work"), { recursive: true });
    await mkdir(installDir, { recursive: true });

    const result = await runUninstall({
      mode: "purge",
      yes: true,
      homeDir,
      profileId: "default",
      installMethodInfo: managedSource(installDir),
      wrapperPaths: [],
      teardownGateway: async () => okTeardown()
    });

    expect(result.exitCode).toBe(0);
    expect(existsSync(join(homeDir, ".estacoda", "profiles", "default"))).toBe(false);
    expect(existsSync(join(homeDir, ".estacoda", "profiles", "work"))).toBe(true);
    expect(result.output).toContain("Preserved 1 other named profile");
  });

  it("skips service-manager teardown on Termux and removes known PREFIX wrapper", async () => {
    const temp = mkdtempSync(join(tmpdir(), "estacoda-uninstall-termux-"));
    const homeDir = join(temp, "home");
    const prefix = join(temp, "com.termux", "usr");
    const wrapper = join(prefix, "bin", "estacoda");
    await mkdir(join(prefix, "bin"), { recursive: true });
    await writeFile(wrapper, "#!/usr/bin/env bash\n# EstaCoda source wrapper. Generated by scripts/install.sh.\n", "utf8");

    const result = await runUninstall({
      homeDir,
      env: { HOME: homeDir, PREFIX: prefix, TERMUX_VERSION: "1" },
      installMethodInfo: manualSource(join(temp, "manual")),
      wrapperPaths: [wrapper]
    });

    expect(result.exitCode).toBe(0);
    expect(existsSync(wrapper)).toBe(false);
    expect(result.output).toContain("Termux detected");
    expect(result.output).toContain("skipped service-manager teardown on Termux");
  });
});

function managedSource(installDir: string): InstallMethodInfo {
  return {
    method: "managed-source",
    source: "stamp",
    installDir,
    sourceUrl: "https://github.com/sifr01-labs/EstaCoda.git",
    branch: "main",
    expectedBranch: "main",
    stampPath: join(installDir, ".install-method.json"),
    recommendedUpdateCommand: "estacoda update",
    canSelfUpdate: true,
    reason: "Install method stamp declares managed-source."
  };
}

function manualSource(installDir: string): InstallMethodInfo {
  return {
    method: "manual-source",
    source: "path",
    installDir,
    recommendedUpdateCommand: "git fetch origin && git status",
    canSelfUpdate: false,
    reason: "A git checkout was detected without a managed-source install stamp."
  };
}

function packageMethod(method: "npm-global" | "pnpm-global" | "homebrew" | "docker"): InstallMethodInfo {
  return {
    method,
    source: method === "docker" ? "container" : method === "homebrew" ? "path" : "package-manager",
    recommendedUpdateCommand: method === "npm-global"
      ? "npm install -g estacoda@latest"
      : method === "pnpm-global"
        ? "pnpm add -g estacoda@latest"
        : method === "homebrew"
          ? "brew upgrade kemetresearch/tap/estacoda"
          : "docker pull ghcr.io/kemetresearch/estacoda:latest",
    canSelfUpdate: false,
    reason: "Detected by test."
  };
}

function okTeardown(): TeardownResult {
  return { ok: true, message: "test teardown" };
}
